packages/devreact/src/App.tsx, packages/examples/create-react-app/src/App.js, packages/sdk-communication-layer/src/RemoteCommunication.ts, packages/sdk/src/provider/SDKProvider.ts, packages/sdk/src/provider/initializeProvider.ts, packages/sdk/src/sdk.ts, yarn.lock
- Remove unnecessary logs
- update yarn.lock with latest changes
=> [feat] log cleanup

packages/examples/create-react-app/package.json, packages/examples/nodejs/package.json, packages/examples/pure-javascript/package.json, packages/examples/react-metamask-button/package.json, packages/examples/reactNativeDemo/package.json, packages/sdk/package.json, yarn.lock
Update sdk dependencies for :
- communication layer
- install modal
Update all examples to sdk 0.2.2
=> feat: update sdk dependencies

yarn.lock
=> fix: dirty lockfile

packages/devreact/src/App.tsx, packages/examples/create-react-app/src/App.js, packages/examples/create-react-app/yarn.lock, packages/examples/nodejs/index.js, packages/examples/nodejs/yarn.lock, packages/sdk/package.json, packages/sdk/src/provider/SDKProvider.ts, packages/sdk/src/sdk.ts, yarn.lock
- remove testUI method in sdk package
- update nodejs example to use session persistence
=> [Fix] invalid esimport nodejs

packages/sdk/src/sdk.ts, packages/sdk/src/utils/shouldInjectProvider.ts
- provider injection fail to detect existing browser plugin when using forceInjectProvider
=> [FIX] provider injection fail to detect existing browser plugin

.gitignore, packages/devreactnative/package.json, packages/devreactnative/yarn.lock, packages/sdk-communication-layer/src/RemoteCommunication.ts, packages/sdk-communication-layer/src/SocketService.ts
- Solve communication protocol issue that prevent reconnection when the wallet crashes.
- Remove 'url undefined' default string
=> [FIX] reconnect on crash rn

packages/devreactnative/package.json, packages/sdk/src/services/RemoteConnection.ts, packages/sdk/src/ui/InstallModal/pendingModal-nodejs.ts, packages/sdk/src/utils/doctypeCheck.ts, packages/sdk/src/utils/documentElementCheck.ts, packages/sdk/src/utils/shouldInjectProvider.ts
- Fix https://github.com/MetaMask/metamask-sdk/issues/89
- Feat: Prevent double otp handling
=> [FIX] nodejs exception #89

packages/devreactnative/package.json, packages/examples/reactNativeDemo/package.json
- remove device name to let auto device detection
=> feat: remove device name for auto detection

packages/devreactnative/App.tsx, packages/sdk-communication-layer/src/RemoteCommunication.ts, packages/sdk-communication-layer/src/SocketService.ts, packages/sdk-communication-layer/src/types/EventType.ts, packages/sdk/src/PostMessageStream/RemoteCommunicationPostMessageStream.ts
[FIX] clean key handshake when socket reconnects (ios / rn)
Not a blocking issue, but cleaning the handshake status always to recover everytime.
=> [FIX] clean key handshake when socket reconnects (ios / rn)

packages/examples/create-react-app/package.json, packages/examples/create-react-app/yarn.lock, packages/examples/nodejs/index.js, packages/examples/nodejs/package.json, packages/examples/nodejs/yarn.lock, packages/examples/pure-javascript/index.html, packages/examples/pure-javascript/package.json, packages/examples/pure-javascript/yarn.lock, packages/examples/reactNativeDemo/package.json, packages/examples/reactNativeDemo/yarn.lock, packages/sdk-communication-layer/package.json, packages/sdk-communication-layer/src/KeyExchange.ts, packages/sdk/package.json, packages/sdk/src/PostMessageStream/RemoteCommunicationPostMessageStream.ts
- add extra info in messages
- update examples to use latest sdk
=> [FEAT] improve logging + update examples

package.json, packages/sdk-communication-layer/CHANGELOG.md, packages/sdk-communication-layer/package.json, packages/sdk-install-modal-web/package.json, packages/sdk/CHANGELOG.md, packages/sdk/package.json, scripts/validate-changelog.sh, yarn.lock
This is the RC branch to test before release.
=> Release 1.0.0

.github/workflows/lint-build-test.yml
Remove node v14 from CI workflow.
=> [FEAT] drop support for node14

package.json, packages/sdk-communication-layer/CHANGELOG.md, packages/sdk-communication-layer/package.json, packages/sdk-communication-layer/src/Analytics.ts, packages/sdk-communication-layer/src/RemoteCommunication.ts, packages/sdk-communication-layer/src/config.ts, packages/sdk-install-modal-web/CHANGELOG.md, packages/sdk-install-modal-web/package.json, packages/sdk/CHANGELOG.md, packages/sdk/package.json, packages/sdk/src/provider/SDKProvider.ts, packages/sdk/src/services/RemoteConnection.ts, packages/sdk/src/types/PlatformType.ts, packages/sdk/tsconfig.json
Reverts MetaMask/metamask-sdk#129
=> Revert "Release 2.0.0"

.gitignore, package.json, packages/examples/create-react-app/package.json, packages/examples/create-react-app/yarn.lock, packages/examples/nextjs-demo/package.json, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk/CHANGELOG.md, packages/sdk/package.json
- update missing types in SDK
- release sdk-react
=> Release 3.0.0

packages/sdk-install-modal-web/src/PendingModal.tsx, packages/sdk/src/Platform/Platfform.ts
=> [fix] #145 missing css color

package.json, packages/sdk-communication-layer/CHANGELOG.md, packages/sdk-communication-layer/package.json, packages/sdk-communication-layer/src/RemoteCommunication.ts, packages/sdk/CHANGELOG.md, packages/sdk/package.json
This reverts commit fed8db64f17689834f2d1c774e9cd1d096385b1a.
=> Revert "Release 7 (#177)"

package.json, packages/sdk/CHANGELOG.md, packages/sdk/package.json
=> Release 9.0.0

package.json, yarn.lock
Rename root package.json name to "metamask-sdk-monorepo"
=> chore: rename root sdk monorepo package name

packages/examples/create-react-app/package.json, packages/examples/create-react-app/src/App.js, packages/examples/create-react-app/yarn.lock, packages/examples/nextjs-demo/package.json, packages/examples/nextjs-demo/yarn.lock, packages/examples/nodejs/package.json, packages/examples/nodejs/yarn.lock, packages/examples/reactNativeDemo/App.tsx, packages/examples/reactNativeDemo/package.json, packages/examples/reactNativeDemo/yarn.lock
=> feat: update examples to 0.4.1

packages/sdk/src/index.ts, packages/sdk/src/sdk.ts
Expose sdk provider class/type.
=> feat: expose sdk provider

packages/sdk-communication-layer/src/RemoteCommunication.ts
Add metamask-mobile platform-type for wallet compatibility
=> feat: add metamask-mobile platform-type for wallet compatibility

packages/devnext/src/pages/_app.tsx, packages/devnext/src/pages/index.tsx, packages/sdk-react/src/MetaMaskProvider.tsx, packages/sdk/src/sdk.ts, packages/sdk/src/services/RemoteConnection.ts
- Switch between extension and sdk provider
https://github.com/MetaMask/metamask-sdk/assets/107169956/b8f7a4ee-13e3-4504-bee4-3434c449df82
=> feat: switch between extension and mobile provider

README.md, packages/devnext/src/pages/_app.tsx, packages/devnext/src/pages/index.tsx, packages/devnext/src/pages/uikit.tsx, packages/devreact/src/App.tsx, packages/sdk-communication-layer/src/RemoteCommunication.ts, packages/sdk-communication-layer/src/types/EventType.ts, packages/sdk-react/.eslintrc.js, packages/sdk-react/package.json, packages/sdk-react/src/MetaMaskButton/MetaMaskButton.tsx, packages/sdk-react/src/MetaMaskConnector.ts, packages/sdk-react/src/MetaMaskHooks.ts, packages/sdk-react/src/MetaMaskProvider.tsx, packages/sdk/src/provider/initializeProvider.ts, packages/sdk/src/sdk.ts, packages/sdk/src/services/RemoteConnection.ts, yarn.lock
- make sdk init function public async (will allow to have platform specific initialization)
- update sdk-react linters and sdk references
=> feat: sdk async init

packages/sdk-communication-layer/src/RemoteCommunication.ts
- fix: possible dangling promise on sendMessage (wallet side)
=> fix: possible dangling promise on sendMessage (wallet side)

packages/sdk/src/sdk.ts
=> feat: autoextract favicon on web platforms

packages/sdk-communication-layer/src/index.ts
feat: export sendanalytics from comm layer
=> feat: export sendanalytics from comm layer

packages/sdk-communication-layer/src/Analytics.ts, packages/sdk-communication-layer/src/RemoteCommunication.ts, packages/sdk-communication-layer/src/index.ts, packages/sdk-communication-layer/src/types/DappMetadata.ts, packages/sdk-communication-layer/src/types/OriginatorInfo.ts, packages/sdk-communication-layer/src/types/TrackingEvent.ts, packages/sdk/src/constants.ts, packages/sdk/src/sdk.ts, packages/sdk/src/services/RemoteConnection.ts
- Track browser extension events
- Track inappbrowser events
- Add source to track origin of sdk connector (eg:wagmi)
=> feat: improved event tracking for extension and inappbrowser

packages/examples/create-react-app/package.json, packages/examples/create-react-app/yarn.lock, packages/examples/nextjs-demo/package.json, packages/examples/nextjs-demo/yarn.lock, packages/examples/nodejs/package.json, packages/examples/nodejs/yarn.lock, packages/examples/pure-javascript/index.html, packages/examples/pure-javascript/package.json, packages/examples/reactNativeDemo/package.json, packages/examples/reactNativeDemo/yarn.lock
feat: update examples to 0.5.0
=> feat: update examples to 0.5.0

packages/devnext/src/pages/index.tsx, packages/sdk-install-modal-web/src/InstallModal.tsx, packages/sdk-install-modal-web/src/ModalLoader.tsx, packages/sdk-install-modal-web/src/PendingModal.tsx, packages/sdk-install-modal-web/src/SelectModal.tsx, packages/sdk-react/src/MetaMaskConnector.ts, packages/sdk/src/sdk.ts, packages/sdk/src/services/RemoteConnection.ts, packages/sdk/src/ui/InstallModal/InstallModal-nodejs.ts, packages/sdk/src/ui/InstallModal/InstallModal-nonweb.ts, packages/sdk/src/ui/InstallModal/InstallModal-web.ts, packages/sdk/src/ui/InstallModal/pendingModal-nodejs.ts, packages/sdk/src/ui/InstallModal/pendingModal-web.ts
=> feat: optimize modal rendering and re-use existing node

packages/examples/nodejs/package.json, packages/examples/nodejs/src/index.ts, packages/examples/nodejs/tsconfig.json
=> feat: improve nodejs example

package.json, packages/examples/nodejs/src/index.ts, packages/sdk-install-modal-web/CHANGELOG.md, packages/sdk-install-modal-web/package.json, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk/CHANGELOG.md, packages/sdk/package.json, packages/sdk/src/services/RemoteConnection.ts
- feat: optimize modal rendering and re-use existing node ([#206](https://github.com/MetaMask/metamask-sdk/pull/206))
- feat: optimize modal rendering and re-use existing node ([#206](https://github.com/MetaMask/metamask-sdk/pull/206))
- feat: sdk async init ([#191](https://github.com/MetaMask/metamask-sdk/pull/191))
- feat: switch between extension and mobile provider ([#189](https://github.com/MetaMask/metamask-sdk/pull/189))
- Release 5.0.0 ([#151](https://github.com/MetaMask/metamask-sdk/pull/151))
- [FEAT] choose between extesnion and mobile wallet ([#146](https://github.com/MetaMask/metamask-sdk/pull/146))
- feat: optimize modal rendering and re-use existing node ([#206](https://github.com/MetaMask/metamask-sdk/pull/206))
=> Release 12.0.0

package.json, packages/examples/nodejs/src/index.ts, packages/sdk-install-modal-web/CHANGELOG.md, packages/sdk-install-modal-web/package.json, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk/CHANGELOG.md, packages/sdk/package.json, packages/sdk/src/services/RemoteConnection.ts
Reverts MetaMask/metamask-sdk#208
=> Revert "Release 12.0.0"

packages/sdk-communication-layer/src/RemoteCommunication.ts, packages/sdk-communication-layer/src/SocketService.ts
- optimize pause/resume connection flow
=> feat: optimize paused/resume flow

packages/devreactnative/src/views/DappView.tsx, packages/sdk/src/services/RemoteConnection.ts
Re-enable correct modal types to prevent calling onClose which was previously removed.
=> fix: invalid modal state

package.json, packages/devnext/src/pages/_app.tsx, packages/devreactnative/App.tsx, packages/sdk-communication-layer/CHANGELOG.md, packages/sdk-communication-layer/package.json, packages/sdk/CHANGELOG.md, packages/sdk/package.json
- feat: optimize paused/resume flow ([#212](https://github.com/MetaMask/metamask-sdk/pull/212))
- fix: invalid modal state ([#213](https://github.com/MetaMask/metamask-sdk/pull/213))
=> Release 13.0.0

README.md
updates README SDK Documentation link
=> fix: updates README SDK Documentation link

packages/sdk/src/config.ts, packages/sdk/src/sdk.ts
Keep track of browser extension preferences in local storage.
=> feat: persist extension provider preferences

package.json, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json
Publish sdk-react to latest sdk
=> Release 15.0.0

packages/devreact/src/App.tsx, packages/devreact/src/index.tsx, packages/devreact/tsconfig.json, packages/examples/create-react-app/package.json, packages/examples/create-react-app/sdk-copy.sh, packages/examples/create-react-app/src/App.tsx, packages/examples/create-react-app/src/index.tsx, packages/examples/create-react-app/tsconfig.json, packages/examples/create-react-app/yarn.lock, packages/sdk-react/src/MetaMaskConnector.ts, packages/sdk-react/src/MetaMaskProvider.tsx, yarn.lock
- fix initialization issue with strictmode
- update examples to use sdk hooks
=> fix: sdk hook connector error with strictmode

packages/sdk/src/sdk.ts
fixes https://github.com/MetaMask/metamask-sdk/issues/231
=> fix: autoconnection setting

packages/sdk/src/provider/initializeProvider.ts, packages/sdk/src/services/RemoteConnection.ts, packages/sdk/src/ui/InstallModal/InstallModal-web.ts
issue of connection terminating early with wagmi
=> fix: install modal unmount

package.json, packages/examples/README.md, packages/sdk/CHANGELOG.md, packages/sdk/package.json
- fix: install modal unmount ([#241](https://github.com/MetaMask/metamask-sdk/pull/241))
=> Release 17.0.0

package.json, packages/sdk/CHANGELOG.md, packages/sdk/package.json, packages/sdk/src/provider/initializeProvider.ts
- feat: optimize provider initialization
=> Release 18.0.0

packages/sdk/CHANGELOG.md, packages/sdk/src/provider/SDKProvider.ts, packages/sdk/src/sdk.ts, packages/sdk/src/services/RemoteConnection.ts
Make sure to early force the connected state in the provider as soon as the session is authorized.
=> feat: force provider connect state

packages/devnext/src/pages/uikit.tsx, packages/examples/react-metamask-button/src/App.js, packages/examples/react-metamask-button/src/index.js, packages/sdk-react/src/MetaMaskButton/MetaMaskButton.tsx, packages/sdk-react/src/MetaMaskConnector.ts, packages/sdk-react/src/MetaMaskProvider.tsx, packages/sdk/src/sdk.ts
- depends on https://github.com/MetaMask/metamask-sdk/pull/245
=> feat: react hooks with wagmi

package.json, packages/devnext/src/pages/_app.tsx, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk/CHANGELOG.md
- feat: force provider connect state ([#245](https://github.com/MetaMask/metamask-sdk/pull/245))
- feat: optimize provider initialization ([#243](https://github.com/MetaMask/metamask-sdk/pull/243))
- feat: react hooks with wagmi ([#246](https://github.com/MetaMask/metamask-sdk/pull/246))
=> Release 19.0.0

packages/sdk/src/provider/initializeProvider.ts, packages/sdk/src/services/RemoteConnection/EventListeners/setupListeners.ts
feat: remove invalid connect event (should contain chainId)
=> feat: remove invalid connect event (should contain chainId)

packages/sdk/src/sdk.ts
Cleanup init state after termination to force reset the modal windows.
=> feat: reinitialize sdk on termination

packages/sdk-communication-layer/src/RemoteCommunication.ts, packages/sdk-communication-layer/src/services/RemoteCommunication/ConnectionManager/initCommunicationLayer.ts, packages/sdk-communication-layer/src/services/RemoteCommunication/ConnectionManager/originatorSessionConnect.ts, packages/sdk-communication-layer/src/services/RemoteCommunication/EventListeners/handleClientsConnectedEvent.ts, packages/sdk-communication-layer/src/services/RemoteCommunication/EventListeners/handleKeysExchangedEvent.ts, packages/sdk-communication-layer/src/types/TrackingEvent.ts, packages/sdk/src/sdk.ts, packages/sdk/src/services/RemoteConnection/EventListeners/setupListeners.ts, packages/sdk/src/services/RemoteConnection/RemoteConnection.ts
Improved analytics to dissociate mobile vs dapp connection event.
Add tracking of authorized and rejected event.
=> feat: improved event tracking

package.json, scripts/sdk-comm-layer-mobile-overwrite.sh, yarn.lock
feat: read param from env file before replacing wallet modules
=> feat: read param from env file before replacing wallet modules

package.json, packages/sdk-communication-layer/CHANGELOG.md, packages/sdk-communication-layer/package.json, packages/sdk-react-ui/CHANGELOG.md, packages/sdk-react-ui/README.md, packages/sdk-react-ui/package.json, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk/CHANGELOG.md, packages/sdk/package.json
Reverts MetaMask/metamask-sdk#291
=> Revert "Release 20.0.0"

package.json, packages/sdk-communication-layer/CHANGELOG.md, packages/sdk-communication-layer/package.json, packages/sdk-install-modal-web/CHANGELOG.md, packages/sdk-install-modal-web/package.json, packages/sdk-react-ui/CHANGELOG.md, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk/CHANGELOG.md, packages/sdk/package.json, yarn.lock
Reverts MetaMask/metamask-sdk#308
=> Revert "Release 22.0.0"

package.json, packages/sdk-communication-layer/CHANGELOG.md, packages/sdk-communication-layer/package.json, packages/sdk-install-modal-web/CHANGELOG.md, packages/sdk-install-modal-web/package.json, packages/sdk-react-ui/CHANGELOG.md, packages/sdk-react-ui/package.json, packages/sdk-react/package.json, packages/sdk/CHANGELOG.md, packages/sdk/package.json
Reverts MetaMask/metamask-sdk#312
=> Revert "feat: release 23.0.0"

package.json, packages/sdk-react-ui/CHANGELOG.md, packages/sdk-react-ui/package.json, packages/sdk-react/package.json
- refactor: move wagmi to sdk-react-ui ([#271](https://github.com/MetaMask/metamask-sdk/pull/271))
- intial project setup
=> Release 24.0.0

package.json, packages/sdk-communication-layer/CHANGELOG.md, packages/sdk-communication-layer/package.json, packages/sdk-install-modal-web/CHANGELOG.md, packages/sdk-install-modal-web/package.json, packages/sdk-react-ui/CHANGELOG.md, packages/sdk-react-ui/package.json, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk/CHANGELOG.md, packages/sdk/package.json
- feat: refactor MetaMaskSDK class for enhanced modularity and testability  ([#309](https://github.com/MetaMask/metamask-sdk/pull/309))
- fix: invalid exports
- feat: align versions ([#323](https://github.com/MetaMask/metamask-sdk/pull/323))
=> Release 26.0.0

packages/devnext/.eslintrc.js, packages/devnext/.eslintrc.json, packages/devnext/src/pages/_app.tsx, packages/devnext/src/pages/index.tsx, packages/sdk-react-ui/src/index.ts
Allow sdk-react-ui users to use the exact same hooks as sdk-react.
=> fix: sdk-react-ui doesn't reexport sdk-react hooks

packages/sdk/src/PortStream/MobilePortStream.ts, packages/sdk/src/services/MobilePortStream/onMessage.ts, packages/sdk/src/services/MobilePortStream/write.ts
This PR refactors the MobilePortStream Class to enhance modularity, readability, and testability.
Having methods in their own files makes unit testing easier.
So we decided to follow this approach in the new module.
🧪 Following the refactor, these tests were performed to validate that everything is still working correctly:
Android Mobile App
DeepLinks works with devreactnative
NodeJs example app works (scanning QR code)
devnext works (scanning QR code)
IOS Mobile App
DeepLinks works with the devreactnative project
NodeJs example app works (scanning QR code)
devnext works (scanning QR code)
Extension
It works with the devnext project
=> feat: refactor the MobilePortStream class

packages/sdk-react-ui/README.md, packages/sdk-react/README.md
docs: add readme info for sdk-react and sdk-react-ui
=> docs: add readme info for sdk-react and sdk-react-ui

README.md
This pull request adds the Codecov badge to our README.
By displaying the badge, we provide immediate visibility into our project's code health and test coverage.
The result is not only better coding practices but also a boost in confidence among contributors and users.
As coverage changes, the badge will dynamically reflect them. 🧪
=> feat: add the Codecov badge into README file

package.json, packages/devreactnative/App.tsx, packages/devreactnative/src/types/env.d.ts, packages/devreactnative/src/views/DappView.tsx, packages/sdk-communication-layer/CHANGELOG.md, packages/sdk-communication-layer/package.json, packages/sdk-communication-layer/src/ECIES.ts, packages/sdk-communication-layer/src/KeyExchange.ts, packages/sdk-install-modal-web/CHANGELOG.md, packages/sdk-install-modal-web/package.json, packages/sdk-install-modal-web/src/ModalLoader.tsx, packages/sdk-react-ui/CHANGELOG.md, packages/sdk-react-ui/package.json, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk-react/src/MetaMaskProvider.tsx, packages/sdk/CHANGELOG.md, packages/sdk/package.json, packages/sdk/src/services/RemoteConnection/ModalManager/reconnectWithModalOTP.ts, packages/sdk/src/services/RemoteConnection/RemoteConnection.ts, packages/sdk/src/services/rpc-requests/RPCRequestHandler.ts, packages/sdk/src/ui/InstallModal/InstallModal-web.ts, packages/sdk/src/ui/InstallModal/pendingModal-web.test.ts, packages/sdk/src/ui/InstallModal/pendingModal-web.ts
Reverts MetaMask/metamask-sdk#354
=> Revert "Release 28.0.0"

packages/sdk/src/sdk.ts
Adds description for each SDKOption
=> feat: adds description for each SDKOption

docs/contributing.md
Updates the `CONTRIBUTING.md` file with team principles:
- Engineering Principles: https://github.com/MetaMask/contributor-docs/blob/main/docs/engineering-principles.md
- Secure Development Lifecycle Policy: https://github.com/MetaMask/contributor-docs/blob/main/docs/sdlc.md
- Guide to Pull Requests: https://github.com/MetaMask/contributor-docs/blob/main/docs/pull-requests.md
- Unit Testing Guidelines: https://github.com/MetaMask/contributor-docs/blob/main/docs/unit-testing.md
- JavaScript Guidelines: https://github.com/MetaMask/contributor-docs/blob/main/docs/javascript.md
- TypeScript Guidelines: https://github.com/MetaMask/contributor-docs/blob/main/docs/typescript.md
=> docs: updates the `CONTRIBUTING.md` file with team principles

README.md, packages/sdk/README.md
updates documentation links and platform status
=> feat: updates documentation links and platform status

README.md, packages/sdk-communication-layer/README.md, packages/sdk-react-ui/README.md, packages/sdk-react/README.md, packages/sdk/README.md
Adds contact form to npm packages.
[Contact form URL](https://fq1an8d8ib2.typeform.com/to/sC7eK5F1)
=> feat: adds contact form to npm packages

packages/devnext/src/pages/index.tsx, packages/sdk-react/src/MetaMaskProvider.tsx
feat: add extensionActive info into hook
=> feat: add extensionActive info into hook

packages/devnext/src/pages/index.tsx, packages/sdk/src/services/rpc-requests/RPCRequestHandler.ts
feat: enable infura http headers for analytics
=> feat: enable infura http headers for analytics

.github/workflows/lint-build-test.yml, package.json, packages/sdk-communication-layer/CHANGELOG.md, packages/sdk-communication-layer/package.json, packages/sdk-react-ui/CHANGELOG.md, packages/sdk-react-ui/package.json, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk/CHANGELOG.md, packages/sdk/package.json, yarn.lock
- feat: enable infura http headers for analytics ([#387](https://github.com/MetaMask/metamask-sdk/pull/387))
- feat: cache selected account and selected chain ([#385](https://github.com/MetaMask/metamask-sdk/pull/385))
- feat: adds contact form to npm packages ([#382](https://github.com/MetaMask/metamask-sdk/pull/382))
- feat: updates documentation links and platform status ([#378](https://github.com/MetaMask/metamask-sdk/pull/378))
- feat: adds contact form to npm packages ([#382](https://github.com/MetaMask/metamask-sdk/pull/382))
- feat: update account and chain values in sdk hook on extension ([#386](https://github.com/MetaMask/metamask-sdk/pull/386))
- feat: add extensionActive info into hook ([#384](https://github.com/MetaMask/metamask-sdk/pull/384))
- feat: adds contact form to npm …
=> Release 30.0.0

.github/workflows/lint-build-test.yml
feat: update github actions to node 18
=> feat: update github actions to node 18

packages/devnext/src/pages/index.tsx, packages/sdk-react/src/MetaMaskProvider.tsx
Faciliate balance computation from react hooks ` const { balance } = useSDK() `
=> feat: automatically compute account balance and return from sdk-react

packages/devnext/.eslintrc.js, packages/devnext/package.json, packages/devnext/src/abi/Simple.json, packages/devnext/src/pages/_app.tsx, packages/devreactnative/App.tsx, packages/devreactnative/ios/Podfile.lock, packages/devreactnative/ios/devreactnative.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, packages/devreactnative/src/views/DappView.tsx, yarn.lock
- configure eslint on devnext
- change devreactnative connect flow and update lockfile
=> chore: misc dev setup config

packages/sdk-install-modal-web/src/InstallModal.tsx, packages/sdk-install-modal-web/src/ModalLoader.tsx, packages/sdk-install-modal-web/src/PendingModal.tsx, packages/sdk-install-modal-web/src/SelectModal.tsx, packages/sdk-install-modal-web/src/components/SDKVersion.tsx, packages/sdk/src/ui/InstallModal/InstallModal-web.ts, packages/sdk/src/ui/InstallModal/pendingModal-web.ts, yarn.lock
feat: add sdk version and change modal order
=> feat: add sdk version and change modal order

packages/examples/create-react-app/package.json, packages/examples/create-react-app/yarn.lock, packages/examples/electronjs/package.json, packages/examples/electronjs/yarn.lock, packages/examples/nodejs/package.json, packages/examples/nodejs/yarn.lock, packages/examples/pure-javascript/package.json, packages/examples/pure-javascript/yarn.lock, packages/examples/react-metamask-button/package.json, packages/examples/react-metamask-button/yarn.lock, packages/examples/reactNativeDemo/package.json, packages/examples/reactNativeDemo/yarn.lock, packages/examples/vuejs/package.json, packages/examples/vuejs/yarn.lock
feat: update examples to 0.9.0
=> feat: update examples to 0.9.0

packages/devreact/src/App.tsx, packages/examples/create-react-app/src/App.tsx, packages/examples/create-react-app/src/index.tsx, packages/sdk-react/src/MetaMaskProvider.tsx
- Fixes an issue that prevent auto-computing the balance when a new account is detected.
- Add balance to the example react dapps.
- enable i18n in example react dapp
=> fix: balance only display when debug is set

packages/examples/create-react-app/package.json, packages/examples/create-react-app/yarn.lock, packages/examples/electronjs/package.json, packages/examples/electronjs/yarn.lock, packages/examples/nextjs-demo/package.json, packages/examples/nextjs-demo/yarn.lock, packages/examples/nodejs/package.json, packages/examples/nodejs/yarn.lock, packages/examples/pure-javascript/package.json, packages/examples/pure-javascript/yarn.lock, packages/examples/react-metamask-button/package.json, packages/examples/react-metamask-button/yarn.lock, packages/examples/reactNativeDemo/package.json, packages/examples/reactNativeDemo/yarn.lock, packages/examples/vuejs/package.json, packages/examples/vuejs/yarn.lock
Update examples to latest sdk version.
=> feat: upgrade sdk to 0.10.0

packages/devnext/src/components/WalletActions.tsx, packages/devnext/src/components/rpcchain-viewer.tsx, packages/devnext/src/pages/index.tsx, packages/devnext/src/styles/globals.css, packages/sdk/src/config.ts, packages/sdk/src/provider/WrapExtensionProvider.ts, packages/sdk/src/services/MetaMaskSDK/InitializerManager/setupExtensionPreferences.ts, packages/sdk/src/utils/get-browser-extension.ts
Possibility to chain multiple rpc calls in a single call:
```
const rpcs: ChainRPC[] = [{
method: "personal_sign",
params: ["something to sign 1", selectedAddress],
},
{
method: "personal_sign",
params: ["hello world", selectedAddress],
},
{
method: "personal_sign",
params: ["Another one #3", selectedAddress],
}];
const response = await provider?.request({method: 'metamask_chainRPCs', params: rpcs}) as any[];
console.log(`response`, response);
```
=> feat: chaining of rpc calls

packages/sdk/src/services/Analytics.ts, packages/sdk/src/services/MetaMaskSDK/InitializerManager/handleAutoAndExtensionConnections.test.ts, packages/sdk/src/services/MetaMaskSDK/InitializerManager/handleAutoAndExtensionConnections.ts
Add metadata to the sdk_extension_utilized analytics event
=> fix: add metadata to the sdk_extension_utilized analytics event

README.md
- update feature list
- add infura info
=> docs: improve sdk readme

packages/sdk-react/src/MetaMaskProvider.tsx
This is a fix to this issue:
[consensys.zendesk.com/agent/tickets/1090365](http://consensys.zendesk.com/agent/tickets/1090365)
=> fix: chainId is undefined on first connection with extension

package.json, packages/sdk-communication-layer/CHANGELOG.md, packages/sdk-communication-layer/package.json, packages/sdk-install-modal-web/CHANGELOG.md, packages/sdk-install-modal-web/package.json, packages/sdk-react-ui/CHANGELOG.md, packages/sdk-react-ui/package.json, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk/CHANGELOG.md, packages/sdk/package.json
This reverts commit d848698884885ff276dd67326c724ff6014f0657.
=> Revert "Release 34.0.0 (#442)"

packages/sdk-react/src/MetaMaskProvider.tsx
fix setChainId cause a build error
=> fix: setChainId cause a build error

.eslintrc.js, package.json, packages/sdk-communication-layer/CHANGELOG.md, packages/sdk-communication-layer/package.json, packages/sdk-install-modal-web/.eslintrc.js, packages/sdk-install-modal-web/CHANGELOG.md, packages/sdk-install-modal-web/package.json, packages/sdk-react-ui/.eslintrc.js, packages/sdk-react-ui/CHANGELOG.md, packages/sdk-react-ui/package.json, packages/sdk-react/.eslintrc.js, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk/.eslintrc.js, packages/sdk/CHANGELOG.md, packages/sdk/package.json
- feat: enable wagmi config as option ([#447](https://github.com/MetaMask/metamask-sdk/pull/447))
- fix: socket io event handler not initializing properly ([#446](https://github.com/MetaMask/metamask-sdk/pull/446))
- feat: detect qrcode origin on wallet ([#443](https://github.com/MetaMask/metamask-sdk/pull/443))
- feat: rename metamask_chainRPCs to metamask_batch and add unit tests ([#440](https://github.com/MetaMask/metamask-sdk/pull/440))
- fix: add metadata to the sdk_extension_utilized analytics event ([#433](https://github.com/MetaMask/metamask-sdk/pull/433))
- feat: chaining of rpc calls ([#434](https://github.com/MetaMask/metamask-sdk/pull/434))
- build: optimize rollup output by env ([#450](https://github.com/MetaMask/metamask-sdk/pull/450))
- fix: socket io event handler not …
=> Release 34.0.0

packages/examples/nodejs/src/index.ts, packages/sdk-socket-server/index.ts
=> fix: socket server init

packages/sdk/src/utils/isOldIOS.ts
refactor: rewrite ios browser version detection for improved readibility
=> refactor: rewrite ios browser version detection for improved readibility

packages/sdk-communication-layer/src/RemoteCommunication.ts, packages/sdk-communication-layer/src/SocketService.ts, packages/sdk-communication-layer/src/index.ts, packages/sdk-communication-layer/src/services/RemoteCommunication/ConnectionManager/initCommunicationLayer.test.ts, packages/sdk-communication-layer/src/services/RemoteCommunication/ConnectionManager/initCommunicationLayer.ts, packages/sdk-communication-layer/src/services/SocketService/EventListeners/handleMessage.ts, packages/sdk-communication-layer/src/services/SocketService/MessageHandlers/trackRpcMethod.test.ts, packages/sdk-communication-layer/src/services/SocketService/MessageHandlers/trackRpcMethod.ts, packages/sdk-communication-layer/src/types/CommunicationLayer.ts, packages/sdk-communication-layer/src/types/EventType.ts, packages/sdk-communication-layer/src/utils/wait.test.ts, packages/sdk-react/src/EventsHandlers/useHandleProviderEvent.test.tsx, packages/sdk-react/src/EventsHandlers/useHandleProviderEvent.ts, packages/sdk-react/src/MetaMaskProvider.spec.tsx, packages/sdk-react/src/MetaMaskProvider.tsx, packages/sdk/src/config.ts, packages/sdk/src/sdk.ts
Allow tracking the list of rpc calls in UI
=> feat: expose rpc history tracker

package.json, packages/sdk-communication-layer/CHANGELOG.md, packages/sdk-communication-layer/package.json, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk/CHANGELOG.md, packages/sdk/jest.config.ts, packages/sdk/package.json, packages/sdk/src/services/RemoteConnection/ConnectionManager/startConnection.ts
- feat: socket handling optimization and devnext ui ([#468](https://github.com/MetaMask/metamask-sdk/pull/468))
- feat: expose rpc history tracker ([#462](https://github.com/MetaMask/metamask-sdk/pull/462))
- refactor: rewrite ios browser version detection for improved readibility ([#465](https://github.com/MetaMask/metamask-sdk/pull/465))
- feat: qrcode deeplinks ([#463](https://github.com/MetaMask/metamask-sdk/pull/463))
- feat: sdk option openDeepLink with dynamic url  ([#464](https://github.com/MetaMask/metamask-sdk/pull/464))
- feat: socket handling optimization and devnext ui ([#468](https://github.com/MetaMask/metamask-sdk/pull/468))
- feat: expose rpc history tracker ([#462](https://github.com/MetaMask/metamask-sdk/pull/462))
- feat: allow editing otherpublickey for faster …
=> Release 37.0.0

packages/sdk/jest.config.ts, packages/sdk/src/services/RemoteConnection/ConnectionManager/connectWithModalInstaller.ts, packages/sdk/src/ui/InstallModal/InstallModal-web.ts
Generate different qrcode based on preferences for the install modal.
=> feat: installmodal deeplink compatibility

packages/sdk-communication-layer/jest.config.ts, packages/sdk-react/jest.config.ts, packages/sdk/jest.config.ts, packages/sdk/src/services/RemoteConnection/ConnectionManager/startConnection.ts
set coverage goal to 50% temporarily
=> feat: set minimum required coverage to 50/100

packages/sdk/src/sdk.ts
feat: expose sdk version
```
sdk.getVersion()
```
=> feat: expose sdk version

packages/examples/with-web3onboard/package.json, packages/examples/with-web3onboard/yarn.lock, packages/sdk/src/sdk.ts
=> feat: update onboard package

packages/examples/create-react-app/package.json, packages/examples/create-react-app/yarn.lock, packages/examples/electronjs/package.json, packages/examples/electronjs/yarn.lock, packages/examples/nextjs-demo/package.json, packages/examples/nextjs-demo/yarn.lock, packages/examples/nodejs/package.json, packages/examples/nodejs/yarn.lock, packages/examples/pure-javascript/package.json, packages/examples/pure-javascript/yarn.lock, packages/examples/react-metamask-button/package.json, packages/examples/react-metamask-button/yarn.lock, packages/examples/react-with-custom-modal/package.json, packages/examples/react-with-custom-modal/yarn.lock, packages/examples/reactNativeDemo/package.json, packages/examples/reactNativeDemo/yarn.lock, packages/examples/vuejs/package.json, packages/examples/vuejs/src/components/MetaMaskComponent.vue, packages/examples/vuejs/yarn.lock
=> feat: Update all examples 0.12.0

packages/devnext/src/pages/index.tsx, packages/devreactnative/App.tsx, packages/devreactnative/package.json, packages/devreactnative/src/views/DappView.tsx, packages/devreactnative/yarn.lock
- Add batch methods in ui for devreactnative
- Overall ui flow improvements for easier debug
=> feat: devreactnative flow

package.json, packages/sdk-communication-layer/CHANGELOG.md, packages/sdk-communication-layer/package.json, packages/sdk-install-modal-web/CHANGELOG.md, packages/sdk-install-modal-web/package.json, packages/sdk-react-ui/CHANGELOG.md, packages/sdk-react-ui/package.json, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk/CHANGELOG.md, packages/sdk/package.json
Reverts MetaMask/metamask-sdk#497
=> Revert "Release 38.0.0"

.github/workflows/publish-release.yml
update publish release action to latest version
=> feat: update publish release action to latest version

packages/sdk-lab/package.json, packages/sdk-react-ui/package.json, packages/sdk-react/package.json
fix: invalid changelog linter script
=> fix: invalid changelog linter script

packages/sdk-lab/package.json, packages/sdk-ui/README.md, packages/sdk-ui/package.json
chore: enable sdk-ui and sdk-lab to v0.1.0
=> chore: enable sdk-ui and sdk-lab to v0.1.0

packages/sdk-react/src/MetaMaskProvider.tsx
Useful to provide better UI feedback to user.
=> feat: add processing state when computing balance

deployments/dapps/create-react-app/Dockerfile, deployments/dapps/create-react-app/package.json, deployments/dapps/create-react-app/yarn.lock, packages/examples/create-react-app/package.json, packages/examples/create-react-app/src/index.tsx, packages/examples/create-react-app/yarn.lock, packages/examples/electronjs/package.json, packages/examples/nextjs-demo/package.json, packages/examples/nextjs-demo/src/app/SDKContainer.tsx, packages/examples/nextjs-demo/yarn.lock, packages/examples/nodejs/package.json, packages/examples/nodejs/src/index.ts, packages/examples/nodejs/yarn.lock, packages/examples/pure-javascript/package.json, packages/examples/pure-javascript/yarn.lock, packages/examples/react-metamask-button/package.json, packages/sdk-lab/package.json, packages/sdk-ui/package.json, packages/sdk-ui/src/components/metamask-button/metamask-button.tsx, packages/sdk-ui/src/components/sdk-summary/sdk-summary.tsx, packages/sdk-ui/src/index.ts
- update examples and set publish config for next version
=> feat: update examples 0.12.2

packages/sdk-ui/src/components/network-selector/network-selector.tsx, packages/sdk-ui/src/design-system/components/Avatars/Avatar/foundation/AvatarBase/AvatarBase.styles.ts, packages/sdk-ui/src/design-system/components/Badges/BadgeWrapper/BadgeWrapper.styles.ts, packages/sdk-ui/src/design-system/components/Cells/Cell/variants/CellSelect/CellSelect.styles.ts, packages/sdk-ui/src/design-system/components/Form/TextField/TextField.tsx, packages/sdk-ui/src/design-system/components/Overlay/Overlay.styles.ts, packages/sdk-ui/src/utils/networks.ts
Fix ts issues from mobile codebase.
=> fix: initial ts issues from migrating mobile codebase

package.json, packages/sdk-communication-layer/CHANGELOG.md, packages/sdk-communication-layer/package.json, packages/sdk-lab/CHANGELOG.md, packages/sdk-lab/package.json, packages/sdk-react-ui/CHANGELOG.md, packages/sdk-react-ui/package.json, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk-ui/CHANGELOG.md, packages/sdk-ui/package.json, packages/sdk/CHANGELOG.md, packages/sdk/package.json
- fix: regex in setupDappMetadata function ([#528](https://github.com/MetaMask/metamask-sdk/pull/528))
- feat: add the option to add dapp icon in base64 format ([#521](https://github.com/MetaMask/metamask-sdk/pull/521))
- feat: design system part3 ([#527](https://github.com/MetaMask/metamask-sdk/pull/527))
- feat: sdk config context as part of sdk-react ([#529](https://github.com/MetaMask/metamask-sdk/pull/529))
- feat: add the option to add dapp icon in base64 format ([#521](https://github.com/MetaMask/metamask-sdk/pull/521))
=> Release 40.0.0

packages/devnext/src/pages/_app.tsx, packages/devreactnative/App.tsx, packages/devreactnative/src/MainTabNavigator.tsx, packages/devreactnative/src/screens/DemoScreen.tsx, packages/devreactnative/src/screens/SettingsScreen.tsx, packages/sdk-react/src/SDKConfigProvider.tsx
- Allow to set initial values for the sdk config provider
- Integrate settings screen for devreactnative
=> feat: add debug and rn compatibility to config provider

package.json, packages/sdk-communication-layer/CHANGELOG.md, packages/sdk-react-ui/CHANGELOG.md, packages/sdk-react-ui/package.json, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk-ui/CHANGELOG.md, packages/sdk-ui/package.json, packages/sdk/CHANGELOG.md, packages/sdk/package.json
Reverts MetaMask/metamask-sdk#534
=> Revert "Release 41.0.0"

package.json, packages/sdk-install-modal-web/CHANGELOG.md, packages/sdk-lab/CHANGELOG.md, packages/sdk-lab/package.json, packages/sdk-react-ui/CHANGELOG.md, packages/sdk-react-ui/package.json, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk-ui/CHANGELOG.md, packages/sdk-ui/package.json, packages/sdk/CHANGELOG.md, packages/sdk/package.json
- sdk ui release version
- feat: build setup for ui and lab ([#537](https://github.com/MetaMask/metamask-sdk/pull/537))
- feat: publish sdk-ui ([#533](https://github.com/MetaMask/metamask-sdk/pull/533))
- feat: build setup for ui and lab ([#537](https://github.com/MetaMask/metamask-sdk/pull/537))
- feat: build setup for ui and lab ([#537](https://github.com/MetaMask/metamask-sdk/pull/537))
- feat: add debug and rn compatibility to config provider ([#532](https://github.com/MetaMask/metamask-sdk/pull/532))
- feat: build setup for ui and lab ([#537](https://github.com/MetaMask/metamask-sdk/pull/537))
=> Release 41.0.0

packages/sdk-ui/.storybook/preview.tsx, packages/sdk-ui/src/mocks/storybook.mocks.tsx
=> fix: storybook setup

packages/sdk-react-ui/package.json, packages/sdk-react-ui/src/MetaMaskButton/Balance.tsx, packages/sdk-react-ui/src/MetaMaskUIProvider.tsx
fix: balance not updating on metamask button
=> fix: balance not updating on metamask button

packages/sdk-react/src/EventsHandlers/useHandleSDKStatusEvent.ts, packages/sdk-react/src/MetaMaskProvider.spec.tsx, packages/sdk-react/src/MetaMaskProvider.tsx, packages/sdk-react/src/SDKConfigProvider.tsx
feat: expose rpc history and keep track of last call
=> feat: expose rpc history and keep track of last call

deployments/dapps/create-react-app/package.json, deployments/dapps/create-react-app/src/connector/icon.tsx, deployments/dapps/create-react-app/src/connector/onboard-sdk-connector.ts, deployments/dapps/create-react-app/src/index.tsx, deployments/dapps/create-react-app/src/pages/demo.tsx, deployments/dapps/create-react-app/src/pages/onboard.tsx, deployments/dapps/create-react-app/tsconfig.json, deployments/dapps/create-react-app/yarn.lock, packages/devnext/src/pages/demo.tsx
SDK Playground with cross platform UI
=> feat: latest deployment code with sdk 0.14.0

deployments/dapps/create-react-app/package.json, deployments/dapps/create-react-app/src/connector/icon.tsx, deployments/dapps/create-react-app/src/connector/onboard-sdk-connector.ts, deployments/dapps/create-react-app/src/index.tsx, deployments/dapps/create-react-app/src/pages/demo.tsx, deployments/dapps/create-react-app/src/pages/onboard.tsx, deployments/dapps/create-react-app/tsconfig.json, deployments/dapps/create-react-app/yarn.lock, packages/devnext/src/pages/demo.tsx, packages/sdk/src/config.ts
fix: connect with not redirecting
=> fix: connect with not redirecting

deployments/dapps/create-react-app/src/components/layout.tsx, packages/sdk-react/src/SDKConfigProvider.tsx
Remove usedeeplinks as default option with sdk context config.
=> feat: change default options

package.json, packages/sdk-socket-server/package.json, packages/sdk-socket-server/yarn.lock, yarn.lock
Fixes CI issue on `sdk-socket-server` package
=> fix: fix CI issues on socket server package

packages/sdk-react-ui/package.json, yarn.lock
Updates Wagmi dependency on `sdk-react-ui` as a precaution due to the LedgerConnector security vulnerability.
=> update: updates Wagmi dependency on `sdk-react-ui` to 1.4.12

package.json, packages/sdk-communication-layer/CHANGELOG.md, packages/sdk-communication-layer/package.json, packages/sdk-react-ui/CHANGELOG.md, packages/sdk-react-ui/package.json, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk/CHANGELOG.md, packages/sdk/package.json
feat: change the 'enableDebug' option to 'enableAnalytics' ([#604](https://github.com/MetaMask/metamask-sdk/pull/604))
feat: create an auto-translate script for the internationalization files ([#595](https://github.com/MetaMask/metamask-sdk/pull/595))
chore: add expo demo app ([#577](https://github.com/MetaMask/metamask-sdk/pull/577))
feat: change the 'enableDebug' option to 'enableAnalytics' ([#604](https://github.com/MetaMask/metamask-sdk/pull/604))
chore: add expo demo app ([#577](https://github.com/MetaMask/metamask-sdk/pull/577))
feat: change default options with useDeeplinks to false ([#576](https://github.com/MetaMask/metamask-sdk/pull/576))
fix: 'sdk-react-ui' MetaMaskModal is not showing balance ([#593](https://github.com/MetaMask/metamask-sdk/pull/593))
=> Release 46.0.0

packages/examples/expo-demo/package.json, packages/examples/expo-demo/yarn.lock, packages/examples/reactNativeDemo/android/app/src/main/java/com/reactnativedemo/MainActivity.java, packages/examples/reactNativeDemo/package.json, packages/examples/reactNativeDemo/yarn.lock
Update the 'sdk-react' package to version `0.14.2` on the RN and Expo demo examples apps
=> feat: update the 'sdk-react' package to version 0.14.2 on the RN and Expo demo examples apps

docs/E2E_Testing_Guide.md
Update the E2E docs with the RN test dapp BrowserStack paths
=> feat: update docs with RN test dapp paths

packages/sdk/src/provider/initializeMobileProvider.ts
This PR introduces an enhancement to the Infura header configuration by adding the `dAppTitle` field. 
- feat: add dAppTitle to Infura Header for Enhanced dApp Identification #666
=> feat: add dAppTitle to Infura Header for Enhanced dApp Identification

docs/why-infura-wagmi.md
This PR introduces a markdown file, why-infura-wagmi.md, providing guidance on integrating an Infura API key with Wagmi for mobile applications. It addresses Wagmi's limitations with read-only calls on mobile devices and outlines the benefits of using Infura for consistent network access. The document serves as a quick reference for developers to enhance mobile dApp performance and stability.
=> feat: create why-infura-wagmi.md file

package.json, packages/sdk-communication-layer/CHANGELOG.md, packages/sdk-communication-layer/package.json, packages/sdk/CHANGELOG.md, packages/sdk/package.json
- feat: Conditionally Invoke getMobileProvider in setupExtensionPreferences Based on if Mobile Provider is Availabile ([#663](https://github.com/MetaMask/metamask-sdk/pull/663))
- feat: add dAppTitle to Infura Header for Enhanced dApp Identification ([#666](https://github.com/MetaMask/metamask-sdk/pull/666))
- feat: new socket code ([#609](https://github.com/MetaMask/metamask-sdk/pull/609))
=> Release 47.0.0

e2e/src/screens/Dapps/AndroidSDKDappScreen.ts, e2e/src/screens/MetaMask/components/NetworkSwitchedModalComponent.ts, e2e/test/configs/browserstack/wdio.android.app.browserstack.conf.ts, e2e/test/configs/local/wdio.android.app.local.conf.ts, e2e/test/configs/local/wdio.ios.app.local.conf.ts, e2e/test/mocha.hooks.ts, e2e/test/specs/js_sdk.spec.ts
This PR introduces end-to-end testing for the Android-SDK test DApp 
https://github.com/MetaMask/metamask-sdk/assets/61094771/bacfa175-3e93-4e64-8e19-7bc0e8a32608
=> feat: create E2E test for Android SDK Dapp

.github/workflows/e2e-android-sdk-tests.yml, .github/workflows/e2e-js-sdk-android-tests.yml, .github/workflows/e2e-js-sdk-ios-tests.yml
Change the workflows to execute directly in the correct working_directory.
=> chore: fix e2e workflows

packages/devsocket/README.md
Add basic usage doc for `devsocket`
=> docs(devsocket): usage for socket interaction

package.json, packages/sdk-communication-layer/CHANGELOG.md, packages/sdk-communication-layer/package.json, packages/sdk-communication-layer/rollup.config.js, packages/sdk-install-modal-web/package.json, packages/sdk-install-modal-web/rollup.config.js, packages/sdk-ui/CHANGELOG.md, packages/sdk-ui/package.json, packages/sdk/CHANGELOG.md, packages/sdk/package.json, packages/sdk/rollup.config.js
- feat: permission system flow ([#675](https://github.com/MetaMask/metamask-sdk/pull/675))
- feat: allow connect with request_permissions ([#685](https://github.com/MetaMask/metamask-sdk/pull/685))
- chore: disable sourcemaps export
- feat: permission system flow ([#675](https://github.com/MetaMask/metamask-sdk/pull/675))
- feat: permission system flow ([#675](https://github.com/MetaMask/metamask-sdk/pull/675))
- consensys.net -> consensys.io ([#605](https://github.com/MetaMask/metamask-sdk/pull/605))
=> Release 48.0.0

package.json, packages/sdk-communication-layer/CHANGELOG.md, packages/sdk-communication-layer/package.json, packages/sdk-communication-layer/rollup.config.js, packages/sdk-install-modal-web/package.json, packages/sdk-install-modal-web/rollup.config.js, packages/sdk-ui/CHANGELOG.md, packages/sdk-ui/package.json, packages/sdk/CHANGELOG.md, packages/sdk/package.json, packages/sdk/rollup.config.js
Reverts MetaMask/metamask-sdk#684
=> Revert "Release 48.0.0"

packages/deve2e/rollup.config.cjs, packages/sdk-communication-layer/rollup.config.js, packages/sdk-install-modal-web/rollup.config.js, packages/sdk/rollup.config.js
=> chore: sourcemaps

.github/workflows/security-code-scanner.yml, packages/sdk-socket-server-next/package.json, packages/sdk-socket-server-next/src/api-config.ts, packages/sdk-socket-server/package.json, packages/sdk-socket-server/src/api-config.ts, yarn.lock
Code security scanning has been implemented in the repo and detected a few alerts: https://github.com/MetaMask/metamask-sdk/security/code-scanning?page=2
This PR aims to configure the workflow, and implement rate-limiter and improved sanitisation on socket server.
=> feat: implement rate limiter and sanitize input

docs/wagmi-integration.md
Add a Wagmi integration documentation with the MetaMask SDK
=> chore: create a Wagmi integration doc

.github/pull_request_template.md
=> docs: pr template

packages/sdk-communication-layer/.eslintrc.js, packages/sdk-communication-layer/jest-preload.js, packages/sdk-communication-layer/package.json, packages/sdk-install-modal-web/.eslintrc.js, packages/sdk-install-modal-web/jest-preload.js, packages/sdk-install-modal-web/package.json, packages/sdk-react/.eslintrc.js, packages/sdk-react/jest-preload.js, packages/sdk-react/package.json, packages/sdk/.eslintrc.js, packages/sdk/jest-preload.js, packages/sdk/package.json
Disable console logs when running unit tests in CI
=> chore: disable logs when running unit tests in CI

packages/sdk-socket-server-next/.env.sample, packages/sdk-socket-server-next/src/api-config.ts
Socket server with tls capabilities.
=> feat: enable redis tls

packages/sdk-socket-server-next/src/api-config.ts, packages/sdk-socket-server-next/src/socket-config.ts
=> feat: redis error handling

package.json, packages/sdk-ui/CHANGELOG.md, packages/sdk-ui/package.json
- feat: activate sourcemap support in all packages and resolve issues ([#730](https://github.com/MetaMask/metamask-sdk/pull/730))
- Fix/sdk config provider ([#714](https://github.com/MetaMask/metamask-sdk/pull/714))
- feat: expose channel id via hook + expose wallet status via sdk instance ([#704](https://github.com/MetaMask/metamask-sdk/pull/704))
- fix: invalid qrcode url ([#695](https://github.com/MetaMask/metamask-sdk/pull/695))
- feat: automated github pages publication ([#599](https://github.com/MetaMask/metamask-sdk/pull/599))
=> Release 50.0.0

packages/sdk/src/utils/blockedDomainCheck.test.ts, packages/sdk/src/utils/blockedDomainCheck.ts
This pull request removes the need for regex statements which can be error prone. This follows the same approach take in extension (https://github.com/MetaMask/metamask-extension/pull/23134) and mobile (https://github.com/MetaMask/metamask-mobile/pull/8674)
=> refactor(sdk): update blockedDomainCheck to remove regex

.github/workflows/gh-pages.yml, deployments/dapps/sdk-playground/Dockerfile, deployments/dapps/sdk-playground/craco.config.js, deployments/dapps/sdk-playground/package.json, deployments/dapps/sdk-playground/src/index.tsx, deployments/dapps/sdk-playground/src/pages/demo.tsx, deployments/dapps/sdk-playground/yarn.lock, packages/devnext/src/pages/demo.tsx, scripts/build-static-dapps.sh
=> feat: updated demo dapp playground

packages/devnext/src/pages/_app.tsx, packages/sdk-communication-layer/src/Analytics.ts, packages/sdk-communication-layer/src/SocketService.ts, packages/sdk-communication-layer/src/index.ts, packages/sdk-communication-layer/src/services/RemoteCommunication/ConnectionManager/initCommunicationLayer.ts, packages/sdk-communication-layer/src/services/SocketService/MessageHandlers/handleSendMessage.test.ts, packages/sdk-communication-layer/src/services/SocketService/MessageHandlers/handleSendMessage.ts, packages/sdk-communication-layer/src/types/TrackingEvent.ts, packages/sdk-react/src/MetaMaskProvider.tsx, packages/sdk/src/provider/initializeMobileProvider.ts, packages/sdk/src/provider/wrapExtensionProvider.test.ts, packages/sdk/src/provider/wrapExtensionProvider.ts, packages/sdk/src/sdk.test.ts, packages/sdk/src/sdk.ts, packages/sdk/src/services/Analytics.test.ts, packages/sdk/src/services/Analytics.ts, packages/sdk/src/services/MetaMaskSDK/InitializerManager/handleAutoAndExtensionConnections.test.ts, packages/sdk/src/services/MetaMaskSDK/InitializerManager/handleAutoAndExtensionConnections.ts, packages/sdk/src/services/MetaMaskSDK/InitializerManager/performSDKInitialization.ts, packages/sdk/src/services/MetaMaskSDK/InitializerManager/setupAnalytics.test.ts, packages/sdk/src/services/MetaMaskSDK/InitializerManager/setupAnalytics.ts, packages/sdk/src/services/MetaMaskSDK/InitializerManager/setupExtensionPreferences.ts, packages/sdk/src/utils/get-browser-extension.test.ts, packages/sdk/src/utils/get-browser-extension.ts
Track all rpc events when analytics is enabled.
https://app.zenhub.com/workspaces/metamask-sdk-6359297a36f20292c13feca0/issues/gh/metamask/metamask-sdk/736
=> feat: rpc event tracking

packages/sdk/src/sdk.ts
Fixes issue on sdk-react-ui with invalid provider state.
=> fix: invalid provider state to undefined instead of null

packages/sdk/src/config.ts, packages/sdk/src/provider/extensionConnectWithOverwrite.test.ts, packages/sdk/src/provider/extensionConnectWithOverwrite.ts, packages/sdk/src/provider/initializeMobileProvider.ts
Isolate logic to overwrite `metamask_connectWith` on the extension.
=> feat: separately handle extension connectWith

packages/devnext/src/components/layout.tsx, packages/sdk-ui/src/components/floating-metamask-button/floating-metamask-button.tsx
Allow to add dynamic action to the MetaMask floating button.
=> feat: allow custom actions in MetaMask floating button

packages/examples/create-react-app/package.json, packages/examples/create-react-app/yarn.lock, packages/examples/electronjs/package.json, packages/examples/electronjs/yarn.lock, packages/examples/expo-demo/package.json, packages/examples/expo-demo/yarn.lock, packages/examples/nextjs-demo/package.json, packages/examples/nextjs-demo/yarn.lock, packages/examples/nodejs/package.json, packages/examples/nodejs/yarn.lock, packages/examples/pure-javascript/package.json, packages/examples/pure-javascript/yarn.lock, packages/examples/react-with-custom-modal/package.json, packages/examples/react-with-custom-modal/yarn.lock, packages/examples/reactNativeDemo/package.json, packages/examples/reactNativeDemo/yarn.lock, packages/examples/vuejs/package.json, packages/examples/vuejs/yarn.lock, packages/sdk-react-ui/src/hooks/MetaMaskWagmiHooks.ts
Update the examples apps to the latest SDK version `0.17.2`
=> feat: update the examples apps to the latest sdk version '0.17.2'

packages/sdk-communication-layer/src/services/SocketService/EventListeners/handleMessage.ts
=> fix: add correct param to sdk_rpc_request_received

package.json, packages/sdk-communication-layer/CHANGELOG.md, packages/sdk-communication-layer/package.json, packages/sdk/CHANGELOG.md, packages/sdk/package.json
- feat: store account between refresh ([#779](https://github.com/MetaMask/metamask-sdk/pull/779))
- fix: add correct param to sdk_rpc_request_received ([#781](https://github.com/MetaMask/metamask-sdk/pull/781))
- feat: add rpc received event ([#780](https://github.com/MetaMask/metamask-sdk/pull/780))
- feat: store account between refresh ([#779](https://github.com/MetaMask/metamask-sdk/pull/779))
=> Release 55.0.0

packages/sdk/src/constants.ts, packages/sdk/src/utils/eip6963RequestProvider.ts
Update the EIP_6369 provider info
=> fix: update the EIP_6369 provider info

packages/sdk/src/services/MetaMaskSDK/ConnectionManager/connect.ts, packages/sdk/src/services/MetaMaskSDK/InitializerManager/setupAnalytics.ts
Currently MetaMask sdk optino enableAnalytics is not working properly, this PR fixes it.
=> fix: issue preventing opting out of analytics

packages/devnext/src/pages/_app.tsx, packages/devnext/src/pages/demo.tsx, packages/sdk/src/Platform/MetaMaskInstaller.test.ts, packages/sdk/src/Platform/MetaMaskInstaller.ts, packages/sdk/src/provider/SDKProvider.ts, packages/sdk/src/provider/initializeMobileProvider.ts, packages/sdk/src/sdk.test.ts, packages/sdk/src/sdk.ts, packages/sdk/src/services/MetaMaskInstaller/redirectToProperInstall.test.ts, packages/sdk/src/services/MetaMaskInstaller/redirectToProperInstall.ts, packages/sdk/src/services/MetaMaskSDK/ConnectionManager/connect.test.ts, packages/sdk/src/services/MetaMaskSDK/ConnectionManager/connect.ts, packages/sdk/src/services/MetaMaskSDK/InitializerManager/performSDKInitialization.ts, packages/sdk/src/services/MetaMaskSDK/InitializerManager/setupExtensionPreferences.ts, packages/sdk/src/services/MetaMaskSDK/InitializerManager/setupRemoteConnectionAndInstaller.test.ts, packages/sdk/src/services/MetaMaskSDK/InitializerManager/setupRemoteConnectionAndInstaller.ts
Fixes a regression after refactor where preferDesktop was creating an error and preventing initialization.
**preferDesktop** option has been deprecated in favor of *extensionOnly*
=> fix: prefer desktop

package.json, packages/sdk-communication-layer/CHANGELOG.md, packages/sdk-communication-layer/package.json, packages/sdk-react-ui/CHANGELOG.md, packages/sdk-react-ui/package.json, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk-ui/CHANGELOG.md, packages/sdk-ui/package.json, packages/sdk/CHANGELOG.md, packages/sdk/package.json
- fix: prefer desktop ([#800](https://github.com/MetaMask/metamask-sdk/pull/800))
- feat: logging initialization ([#799](https://github.com/MetaMask/metamask-sdk/pull/799))
- fix: prefer desktop ([#800](https://github.com/MetaMask/metamask-sdk/pull/800))
- feat: logging initialization ([#799](https://github.com/MetaMask/metamask-sdk/pull/799))
- fix: prefer desktop ([#800](https://github.com/MetaMask/metamask-sdk/pull/800))
- feat: logging initialization ([#799](https://github.com/MetaMask/metamask-sdk/pull/799))
- fix: prefer desktop ([#800](https://github.com/MetaMask/metamask-sdk/pull/800))
- feat: logging initialization ([#799](https://github.com/MetaMask/metamask-sdk/pull/799))
- fix: prefer desktop ([#800](https://github.com/MetaMask/metamask-sdk/pull/800))
- feat: logging …
=> Release 58.0.0

packages/sdk/src/provider/wrapExtensionProvider.ts, packages/sdk/src/services/MetaMaskSDK/InitializerManager/setupExtensionPreferences.ts
Fixes issue on mobile inpageprovider.
=> fix: inpage provider support

package.json, packages/sdk-communication-layer/CHANGELOG.md, packages/sdk-communication-layer/package.json, packages/sdk-install-modal-web/CHANGELOG.md, packages/sdk-install-modal-web/package.json, packages/sdk-react-ui/CHANGELOG.md, packages/sdk-react-ui/package.json, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk/CHANGELOG.md, packages/sdk/package.json
- fix: preferDesktop and onboarding ([#807](https://github.com/MetaMask/metamask-sdk/pull/807))
- fix: inpage provider support ([#806](https://github.com/MetaMask/metamask-sdk/pull/806))
- fix: preferDesktop and onboarding ([#807](https://github.com/MetaMask/metamask-sdk/pull/807))
- fix: inpage provider support ([#806](https://github.com/MetaMask/metamask-sdk/pull/806))
- fix: preferDesktop and onboarding ([#807](https://github.com/MetaMask/metamask-sdk/pull/807))
- fix: inpage provider support ([#806](https://github.com/MetaMask/metamask-sdk/pull/806))
- fix: preferDesktop and onboarding ([#807](https://github.com/MetaMask/metamask-sdk/pull/807))
- fix: preferDesktop and onboarding ([#807](https://github.com/MetaMask/metamask-sdk/pull/807))
=> Release 59.0.0

packages/sdk/src/services/MetaMaskSDK/InitializerManager/setupAnalytics.ts
Improve the validation of `dappId` param in the `setupAnalytics` function
=> fix: improve the validation of 'dappId' param in the 'setupAnalytics' function

package.json, packages/sdk-react-ui/CHANGELOG.md, packages/sdk-react-ui/package.json, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk/CHANGELOG.md, packages/sdk/package.json
- fix: improve the validation of 'dappId' param in the 'setupAnalytics' function ([#817](https://github.com/MetaMask/metamask-sdk/pull/817))
- fix: improve the validation of 'dappId' param in the 'setupAnalytics' function ([#817](https://github.com/MetaMask/metamask-sdk/pull/817))
- fix: improve the validation of 'dappId' param in the 'setupAnalytics' function ([#817](https://github.com/MetaMask/metamask-sdk/pull/817))
=> Release 60.0.0

.gitignore, packages/sdk-socket-server-next/Dockerfile, packages/sdk-socket-server-next/package.json, packages/sdk-socket-server-next/tsconfig.json, packages/sdk/src/config.ts, packages/sdk/src/storage-manager/StorageManagerAS.ts, packages/sdk/src/storage-manager/StorageManagerNode.ts
Fix docker startup and node js storage manager.
=> feat: storage manager

packages/sdk/package.json, yarn.lock
Remove rn dependencies or it may cause issue with NPM users of wagmi (npm install wagmi) to hang on the installation of React Native.
=> feat: remove rn deps

package.json, packages/sdk-communication-layer/CHANGELOG.md, packages/sdk-communication-layer/package.json, packages/sdk-install-modal-web/CHANGELOG.md, packages/sdk-install-modal-web/package.json, packages/sdk-react-ui/CHANGELOG.md, packages/sdk-react-ui/package.json, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk-socket-server-next/package.json, packages/sdk/CHANGELOG.md, packages/sdk/package.json
Reverts MetaMask/metamask-sdk#836
=> Revert "feat: release 62.0.0"

package.json, packages/sdk-communication-layer/CHANGELOG.md, packages/sdk-communication-layer/package.json, packages/sdk-install-modal-web/CHANGELOG.md, packages/sdk-install-modal-web/package.json, packages/sdk-react-ui/CHANGELOG.md, packages/sdk-react-ui/package.json, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk-socket-server-next/package.json, packages/sdk/CHANGELOG.md, packages/sdk/package.json
Reverts MetaMask/metamask-sdk#838
=> Revert "Release 63.0.0"

packages/sdk-communication-layer/CHANGELOG.md, packages/sdk-communication-layer/package.json, packages/sdk-install-modal-web/CHANGELOG.md, packages/sdk-install-modal-web/package.json, packages/sdk-react-ui/CHANGELOG.md, packages/sdk-react-ui/package.json, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk/CHANGELOG.md, packages/sdk/package.json
- feat: track done event on extension analytics ([#834](https://github.com/MetaMask/metamask-sdk/pull/834))
=> Release 62.0.0

package.json, packages/sdk-communication-layer/CHANGELOG.md, packages/sdk-communication-layer/package.json, packages/sdk-install-modal-web/CHANGELOG.md, packages/sdk-install-modal-web/package.json, packages/sdk-react-ui/CHANGELOG.md, packages/sdk-react-ui/package.json, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk/CHANGELOG.md, packages/sdk/package.json
- skip version because of publishing issue
- skip version because of publishing issue
- feat: track done event on extension analytics ([#834](https://github.com/MetaMask/metamask-sdk/pull/834))
=> Release 65.0.0

packages/sdk/src/storage-manager/StorageManagerWeb.test.ts, packages/sdk/src/storage-manager/StorageManagerWeb.ts, packages/sdk/src/storage-manager/getStorageManager.ts
Fixes: failure to start after removing rn dependencies.
We need to maintain the storage manager for web to prevent the issues.
=> feat: re-enable jscc web

package.json, packages/sdk/CHANGELOG.md, packages/sdk/package.json
- feat: re-enable jscc web ([#845](https://github.com/MetaMask/metamask-sdk/pull/845))
=> Release 66.0.0

package.json, packages/sdk-react-ui/CHANGELOG.md, packages/sdk-react-ui/package.json, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk-ui/CHANGELOG.md, packages/sdk-ui/package.json
Align versions of sdk-react and sdk-react-ui.
=> Release 67.0.0

packages/sdk-socket-server-next/src/protocol/handleAck.ts
Add extra logging on socket server.
=> feat: improve logging if parsing error

scripts/build-static-dapps.sh
Fixes redirect url printed incorrectly for the automated github pages.
=> fix: invalid deployment script

packages/sdk-socket-server-next/src/socket-config.ts
Add extra logging to manage socket server backward compatibility.
=> feat: increase logs on socket server

packages/sdk-react-native/package.json
=> feat: update the package.json file of the 'sdk-react-native' package

packages/sdk-react-native/CHANGELOG.md
=> fix: update  CHANGELOG file of the 'sdk-react-native' package

package.json, packages/sdk-react/src/MetaMaskHooks.spec.tsx, packages/sdk-react/src/SDKConfigProvider.test.tsx
=> chore: add unit tests to the sdk-react package

packages/sdk-communication-layer/package.json
=> fix: ref crossfetch

packages/examples/reactNativeSdkDemo/ios/Podfile.lock, packages/examples/reactNativeSdkDemo/ios/reactNativeSdkDemo.xcodeproj/project.pbxproj, packages/examples/reactNativeSdkDemo/package.json, packages/examples/reactNativeSdkDemo/yarn.lock, packages/sdk-react-native/package.json, packages/sdk-react-native/rollup.config.js
update the `reactNativeSdkDemo` example Dapp with the latest version of the `sdk-react-native` package
=> chore: update reactNativeSdkDemo with latest sdk-react-native version

packages/sdk-socket-server-next/src/protocol/handleAck.ts, packages/sdk-socket-server-next/src/protocol/handleJoinChannel.ts, packages/sdk-socket-server-next/src/protocol/handleMessage.ts, packages/sdk-socket-server-next/src/protocol/handlePing.ts, packages/sdk-socket-server-next/src/protocol/retrieveMessages.ts, packages/sdk-socket-server-next/src/socket-config.ts, yarn.lock
In order to allow tracking connection health and actions on relay server we now add a channelId identifier to each log so we can reconstruct history of events easily on grafana
=> feat: add channelId to each log for easier tracking

packages/sdk/src/constants.ts, packages/sdk/src/sdk.ts
Set 'direct' for default sdk source.
=> feat: set default sdk source

packages/sdk-socket-server-next/src/api-config.ts
Default to 'direct' when sdk source is not set.
=> feat: default analytics source on socket server

packages/sdk-socket-server-next/src/api-config.ts, packages/sdk/src/provider/wrapExtensionProvider.ts
Correctly capture rejection event on extension for proper health metrics.
=> fix: extension events

docs/wagmi-integration.md, docs/wagmi-v2-integration.md, packages/examples/wagmi-demo-react/package.json, packages/examples/wagmi-demo-react/src/App.tsx, packages/examples/wagmi-demo-react/src/wagmi.ts, packages/examples/wagmi-demo-react/yarn.lock, packages/examples/wagmi-demo/src/app/page.tsx, packages/examples/wagmi-demo/tsconfig.json
update the `wagmi` example dapps
=> chore: update the wagmi example dapps

.github/workflows/lint-build-test.yml, .github/workflows/main.yml
Update the `codecov-action` version in order to make the CI job work again
=> chore: update the 'codecov-action' version

packages/sdk-communication-layer/src/services/RemoteCommunication/ConnectionManager/initCommunicationLayer.ts
Prevent empty dappId. Empty dappid can still be found in analytics, this PR will help identify in which scenario this situation can happen.
=> feat: prevent empty dappid

.github/workflows/main.yml, .github/workflows/sonar-cloud.yml, sonar-project.properties
This PR adds the SonarCloud CI job. As a first iteration it is only scanning for code quality and skipping all unit tests.
=> chore: adds an initial version of the SonarCloud integration

packages/sdk/src/services/MetaMaskSDK/ConnectionManager/terminate.test.ts
Modify `terminate.ts` unit tests to avoid warnings on PRs
=> chore: modify 'terminate.ts' unit tests to avoid warnings on PRs

package.json, packages/sdk-react-ui/CHANGELOG.md, packages/sdk-react-ui/package.json, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk/CHANGELOG.md, packages/sdk/package.json
- fix: update the 'request' method wrapper logic in 'wrapExtensionProvider' to handle connectAndSign issues ([#913](https://github.com/MetaMask/metamask-sdk/pull/913))
- fix: update the 'request' method wrapper logic in 'wrapExtensionProvider' to handle connectAndSign issues ([#913](https://github.com/MetaMask/metamask-sdk/pull/913))
- fix: update the 'request' method wrapper logic in 'wrapExtensionProvider' to handle connectAndSign issues ([#913](https://github.com/MetaMask/metamask-sdk/pull/913))
=> Release 73.0.0

packages/sdk/src/provider/wrapExtensionProvider.ts
Update the 'request' method in the 'wrapExtensionProvider' to throw an error when RPC calls fail
=> chore: update the 'request' method in the 'wrapExtensionProvider' to throw an error when RPC calls fail

packages/devnext/package.json, packages/sdk-communication-layer/package.json, packages/sdk-install-modal-web/package.json, packages/sdk/package.json, yarn.lock
Aligned `utf-8-validate` package to ^5.0.2 and removed unused `react-i18next` dependency.
This resolves version conflicts and eliminates installation warnings, ensuring smoother installations.
Fixes #821
=> chore: update SDK dependencies to resolve version conflicts

packages/devnext/next.config.js, packages/devnext/package.json, packages/devnext/src/pages/demo.tsx, packages/sdk/package.json, packages/sdk/src/services/Ethereum.ts, yarn.lock
Update the '@metamask/providers' package to version '16.1.0'
=> feat: update the '@metamask/providers' package to version '16.1.0'

packages/sdk-react-native/android/build.gradle, packages/sdk-react-native/metamask-sdk-react-native.podspec
Update the native modules of the `sdk-react-native` package
=> chore: update the 'sdk-react-native' package native modules versions

packages/examples/reactNativeSdkDemo/ios/Podfile.lock, packages/examples/reactNativeSdkDemo/package.json, packages/examples/reactNativeSdkDemo/yarn.lock, packages/sdk-react-native/rollup.config.js
Update the `reactNativeSdkDemo` example to `sdk-react-native` version `0.3.1`
=> chore: update the 'reactNativeSdkDemo' example to 'sdk-react-native' version 0.3.1

package.json, packages/sdk-react-native/CHANGELOG.md, packages/sdk-react-native/package.json
- chore: update 'sdk-react-native' the 'android-sdk' to '0.5.8' ([#942](https://github.com/MetaMask/metamask-sdk/pull/942))
=> Release 76.0.0

packages/examples/reactNativeSdkDemo/src/views/DappView.tsx, packages/sdk-react-native/metamask-sdk-react-native.podspec, packages/sdk-react-native/package.json
Update the 'metamask-ios-sdk' version to '0.7.3' in the 'sdk-react-native' package
=> chore: update the 'metamask-ios-sdk' version to '0.7.3' in the 'sdk-react-native' package

platforms.json
This PR updates the `platforms.json` file to update all versions
N/A
=> chore: Update platforms.json

packages/sdk-communication-layer/src/services/RemoteCommunication/ConnectionManager/initCommunicationLayer.ts, packages/sdk-communication-layer/src/types/DappMetadata.ts, packages/sdk-communication-layer/src/types/OriginatorInfo.ts
Adda a new property called `connector` to to track second level connectors, will be left unset by most, but we will direct some devs to implement it.
=> feat: adds `connector` analytical property

packages/sdk-react/src/SDKConfigProvider.tsx, packages/sdk/src/sdk.ts
Sets `extensionOnly` property by default to true
=> feat: sets extensionOnly default to true

packages/sdk-socket-server-next/package.json, packages/sdk-socket-server-next/src/protocol/handleJoinChannel.ts, packages/sdk-socket-server-next/src/socket-config.ts
Removed immediate deletion of empty rooms and sets TTL for channels hash in handleJoinChannel.ts
Fixes: [#28](https://github.com/MetaMask/sdk-planning/issues/28)
=> fix: TTL for channels hash

packages/devnext/babel.config.js, packages/devnext/package.json, yarn.lock
=> fix: devnext compiling issues

packages/sdk-react-native/android/build.gradle, packages/sdk-react-native/metamask-sdk-react-native.podspec
This PR updates the iOS and Android SDKs in `@metamask/sdk-react-native` to their latest versions. This ensures we are utilizing the most recent features, improvements, and security patches provided by the SDKs.
=> feat: update iOS and Android SDKs to latest versions in 'sdk-react-native'

packages/examples/reactNativeSdkDemo/ios/Podfile.lock, packages/examples/reactNativeSdkDemo/package.json, packages/examples/reactNativeSdkDemo/yarn.lock
update the `sdk-react-native` package to `v0.3.5` in the `reactNativeSdkDemo` dApp
=> chore: update the 'sdk-react-native' package to 'v0.3.5' in the reactNativeSdkDemo dApp

packages/examples/wagmi-demo-react/package.json, packages/examples/wagmi-demo-react/yarn.lock, packages/examples/wagmi-demo/package.json, packages/examples/wagmi-demo/yarn.lock
update the wagmi examples dapps to the latest wagmi version
=> chore: update the wagmi examples dapps to the latest wagmi version

package.json, packages/examples/create-react-app/package.json, packages/examples/create-react-app/yarn.lock, packages/examples/electronjs/package.json, packages/examples/electronjs/yarn.lock, packages/examples/expo-demo/package.json, packages/examples/expo-demo/yarn.lock, packages/examples/nextjs-demo/package.json, packages/examples/nextjs-demo/yarn.lock, packages/examples/nodejs-interactive/package.json, packages/examples/nodejs-interactive/yarn.lock, packages/examples/nodejs/package.json, packages/examples/nodejs/yarn.lock, packages/examples/pure-javascript/package.json, packages/examples/pure-javascript/yarn.lock, packages/examples/react-metamask-button/package.json, packages/examples/react-metamask-button/yarn.lock, packages/examples/react-with-custom-modal/package.json, packages/examples/react-with-custom-modal/yarn.lock, packages/examples/reactNativeDemo/package.json, packages/examples/reactNativeDemo/yarn.lock, packages/examples/vuejs/package.json, packages/examples/vuejs/yarn.lock, packages/examples/with-web3onboard/yarn.lock, scripts/update-examples-dapps.sh
update the example dapps to the latest SDK versions
=> chore: update the example dapps to the latest SDKs versions

packages/devnext/package.json, packages/devnext/src/pages/demo.tsx, yarn.lock
Implemented Sign-In with Ethereum (SIWE) functionality, including message creation, signing, and signature verification.
=> chore: add support for 'siwe' in devnext

package.json, packages/sdk-react-native/CHANGELOG.md, packages/sdk-react-native/package.json
- chore: filter metamask urls ([#987](https://github.com/MetaMask/metamask-sdk/pull/987))
=> Release 80.0.0

packages/sdk-socket-server-next/package.json
ready to update socket server to dev.
=> feat: bump socket server version

package.json, packages/sdk-communication-layer/CHANGELOG.md, packages/sdk-communication-layer/package.json, packages/sdk-communication-layer/src/services/RemoteCommunication/MessageHandlers/onCommunicationLayerMessage.ts, yarn.lock
- feat: full deeplink protocol ([#992](https://github.com/MetaMask/metamask-sdk.git/pull/992))
=> Release 82.0.0

packages/sdk-react-native/android/build.gradle, packages/sdk-react-native/metamask-sdk-react-native.podspec
Update iOS SDK and Android SDK dependencies versions
=> chore: update native sdk versions

package.json, packages/sdk-react-native/CHANGELOG.md, packages/sdk-react-native/package.json
- chore: update native sdk versions ([#997](https://github.com/MetaMask/metamask-sdk/pull/997))
=> Release 83.0.0

packages/examples/create-react-app/sdk-copy.sh, packages/examples/nodejs-interactive/sdk-copy.sh, packages/examples/nodejs/sdk-copy.sh, packages/examples/reactNativeDemo/sdk-copy.sh, packages/examples/vuejs/sdk-copy.sh, packages/examples/wagmi-demo-react/sdk-copy.sh
Improves the performance on SDK_copy.sh scripts by copying the dist folders instead of the whole code for each package.
=> chore: improves performance on sdk_copy script for examples

packages/examples/reactNativeSdkDemo/ios/Podfile.lock, packages/examples/reactNativeSdkDemo/package.json, packages/examples/reactNativeSdkDemo/yarn.lock, packages/sdk-react-native/ios/MetaMaskReactNativeSdk.swift, packages/sdk-react-native/ios/Options.h, packages/sdk-react-native/ios/Options.m, packages/sdk-react-native/metamask-sdk-react-native.podspec, packages/sdk-react-native/package.json, packages/sdk-react-native/src/NativePackageMethods.ts
=> chore: display the right 'rn-sdk' version in the wallet side

packages/examples/reactNativeSdkDemo/ios/Podfile.lock, packages/examples/reactNativeSdkDemo/src/views/DappView.tsx, packages/sdk-react-native/android/build.gradle, packages/sdk-react-native/android/src/main/java/io/metamask/reactnativesdk/MetaMaskReactNativeSdkModule.kt, packages/sdk-react-native/src/MetaMaskProvider.tsx, packages/sdk-react-native/src/NativePackageMethods.ts
This PR adds handling of infura API key when supplied
=> chore: add handling of infura api

packages/sdk-react-native/metamask-sdk-react-native.podspec
Bump ios sdk version to the latest
=> chore: bump ios sdk version

package.json, packages/sdk-react-native/CHANGELOG.md, packages/sdk-react-native/package.json
- chore: bump ios sdk version ([#1027](https://github.com/MetaMask/metamask-sdk/pull/1027))
=> Release 89.0.0

package.json, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk/CHANGELOG.md, packages/sdk/package.json
- fix: invalid display_uri event emitted
=> Release 90.0.0

packages/sdk/src/provider/initializeMobileProvider.ts
=> fix: update the `initializeMobileProvider` function to ensure it returns all connected accounts on mobile

.gitignore, packages/examples/create-react-app/package.json, packages/examples/create-react-app/yarn.lock, packages/examples/electronjs/package.json, packages/examples/electronjs/yarn.lock, packages/examples/expo-demo/package.json, packages/examples/expo-demo/yarn.lock, packages/examples/nextjs-demo/package.json, packages/examples/nextjs-demo/yarn.lock, packages/examples/nodejs-interactive/package.json, packages/examples/nodejs-interactive/yarn.lock, packages/examples/nodejs/package.json, packages/examples/nodejs/yarn.lock, packages/examples/pure-javascript/package.json, packages/examples/pure-javascript/yarn.lock, packages/examples/react-metamask-button/package.json, packages/examples/react-metamask-button/yarn.lock, packages/examples/react-with-custom-modal/package.json, packages/examples/react-with-custom-modal/yarn.lock, packages/examples/reactNativeDemo/package.json, packages/examples/reactNativeDemo/yarn.lock, packages/examples/reactNativeSdkDemo/ios/Podfile.lock, packages/examples/reactNativeSdkDemo/package.json, packages/examples/reactNativeSdkDemo/yarn.lock, packages/examples/vuejs/package.json, packages/examples/vuejs/yarn.lock, packages/examples/wagmi-demo-react/package.json, packages/examples/wagmi-demo-react/yarn.lock, packages/examples/wagmi-demo/package.json
=> chore: update example dapps to latest SDK versions (0.28.4)

package.json, packages/sdk-react-native/CHANGELOG.md, packages/sdk-react-native/package.json
- chore: bump ios sdk version ([#1035](https://github.com/MetaMask/metamask-sdk/pull/1035))
=> Release 92.0.0

packages/sdk-communication-layer/src/services/RemoteCommunication/ConnectionManager/initSocketService.ts, packages/sdk-communication-layer/src/services/RemoteCommunication/EventListeners/handleClientsDisconnectedEvent.test.ts, packages/sdk-communication-layer/src/services/RemoteCommunication/EventListeners/handleClientsDisconnectedEvent.ts, packages/sdk-communication-layer/src/services/RemoteCommunication/EventListeners/handleKeysExchangedEvent.ts, packages/sdk-communication-layer/src/services/SocketService/ConnectionManager/handleJoinChannelResult.ts, packages/sdk-communication-layer/src/services/SocketService/EventListeners/handleMessage.ts, packages/sdk-communication-layer/src/services/SocketService/MessageHandlers/handleSendMessage.ts, packages/sdk-socket-server-next/package.json, packages/sdk-socket-server-next/src/analytics-api.ts, packages/sdk-socket-server-next/src/index.ts, packages/sdk-socket-server-next/src/protocol/handleAck.ts, packages/sdk-socket-server-next/src/protocol/handleChannelRejected.ts, packages/sdk-socket-server-next/src/protocol/handleCheckRoom.ts, packages/sdk-socket-server-next/src/protocol/handleJoinChannel.ts, packages/sdk-socket-server-next/src/protocol/handleMessage.ts, packages/sdk-socket-server-next/src/protocol/retrieveMessages.ts, packages/sdk-socket-server-next/src/redis-check.ts, packages/sdk-socket-server-next/src/socket-config.ts, packages/sdk-socket-server-next/src/utils.ts, packages/sdk/src/services/RemoteConnection/ConnectionManager/startConnection.ts
Fixes events emission and missing dappId from extension.
=> feat: server events and dappid recovery

packages/sdk/src/config.ts
add missing event on extension.
=> feat: missing extension analytics event for personal_sign

packages/sdk-socket-server-next/package.json, packages/sdk-socket-server-next/src/protocol/handleAck.ts, packages/sdk-socket-server-next/src/protocol/handleMessage.ts
- Cleanup code to manage ack
- Return an error via callback to inform clients
=> feat: improve message ack handling

packages/sdk-socket-server-next/src/analytics-api.ts, packages/sdk-socket-server-next/src/protocol/handleJoinChannel.ts
- Fixes: cold start message not containing the id field
- Fixes: hotsharding event on older sdk versions
=> fix: backward compatible socket server

packages/sdk/src/services/Analytics.test.ts
Fixes failing unit tests on main.
=> fix: unit tests

packages/sdk-socket-server-next/package.json, packages/sdk-socket-server-next/src/analytics-api.ts
=> feat: add extra logs for managing cache on server

packages/sdk-socket-server-next/package.json
=> feat: bump socket server version to 2.8.0

packages/sdk-socket-server-next/package.json, packages/sdk-socket-server-next/src/utils.ts
Prevent blocking event that don't have the full set of properties.
=> feat: bump version and prevent empty field restriction

packages/examples/pure-javascript/index.html, packages/examples/pure-javascript/package.json, packages/examples/pure-javascript/sdk-copy.sh, packages/examples/pure-javascript/yarn.lock, packages/sdk/src/services/MetaMaskSDK/InitializerManager/performSDKInitialization.ts
- Fixes the pure js example to latest sdk version and correct url.
- Adjust copy script to copy only required files
- Default to useDeeplink to true
=> feat: default options for pure js and useDeeplink default to true

package.json, packages/sdk-communication-layer/CHANGELOG.md, packages/sdk-communication-layer/package.json, packages/sdk-install-modal-web/CHANGELOG.md, packages/sdk-install-modal-web/package.json, packages/sdk-react-ui/CHANGELOG.md, packages/sdk-react-ui/package.json, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk/CHANGELOG.md, packages/sdk/package.json, packages/sdk/src/services/MetaMaskSDK/InitializerManager/performSDKInitialization.test.ts
- feat: default options for pure js and useDeeplink default to true ([#1070](https://github.com/MetaMask/metamask-sdk/pull/1070))
- feat: default options for pure js and useDeeplink default to true ([#1070](https://github.com/MetaMask/metamask-sdk/pull/1070))
- feat: default options for pure js and useDeeplink default to true ([#1070](https://github.com/MetaMask/metamask-sdk/pull/1070))
- feat: default options for pure js and useDeeplink default to true ([#1070](https://github.com/MetaMask/metamask-sdk/pull/1070))
- feat: default options for pure js and useDeeplink default to true ([#1070](https://github.com/MetaMask/metamask-sdk/pull/1070))
=> Release 96.0.0

scripts/build-static-dapps.sh
Adds debug messages with an improved git branch detection for deployments triggered by a pull request
=> chore: improves the branch detection for separate branch deployment

.github/workflows/e2e-js-sdk-android-tests.yml, .github/workflows/e2e-js-sdk-ios-tests.yml
=> chore: removes references to unused dapps

api.client.http, packages/sdk-socket-server-next/src/analytics-api.ts
- Group analytics events from older sdk clients
- Track segment error when the is an error
=> Fix analytics endpoint

packages/sdk-communication-layer/package.json, packages/sdk-react/package.json, packages/sdk/package.json
revert issue with pipeline blocking release.
=> chore: revert invalid version

packages/examples/react-demo/sdk-copy.sh
This PR enhances the SDK copy script by including the `sdk-install-modal-web` distribution directory in the cleanup process, ensuring a completely clean state before copying new files. The change also adds Vite cache cleanup for better build consistency.
=> chore: enhance sdk copy script cleanup for improved build consistency

packages/sdk-install-modal-web/src/InstallModal.tsx
Added height and maxWidth styles to div elements in InstallModal.tsx for better layout control.
=> style: add inline styles to div elements

package.json, packages/sdk-install-modal-web/CHANGELOG.md, packages/sdk-install-modal-web/package.json, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk/CHANGELOG.md, packages/sdk/package.json
- fix: nextjs build fix pr ([#1163](https://github.com/MetaMask/metamask-sdk/pull/1163))
- Set initial modal tab based on preferDesktop option ([#1158](https://github.com/MetaMask/metamask-sdk/pull/1158))
- fix: nextjs build fix pr ([#1163](https://github.com/MetaMask/metamask-sdk/pull/1163))
- Set initial modal tab based on preferDesktop option ([#1158](https://github.com/MetaMask/metamask-sdk/pull/1158))
- Set initial modal tab based on preferDesktop option ([#1158](https://github.com/MetaMask/metamask-sdk/pull/1158))
=> Release 105.0.0

package.json, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk/CHANGELOG.md, packages/sdk/package.json
- fix(analytics): improve dapp details tracking and SDK RPC request analytics ([#1179](https://github.com/MetaMask/metamask-sdk/pull/1179))
- fix(analytics): improve dapp details tracking and SDK RPC request analytics ([#1179](https://github.com/MetaMask/metamask-sdk/pull/1179))
=> Release 106.0.0

package.json, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk/CHANGELOG.md, packages/sdk/package.json
- refactor(sdk): always send RPC requests via network and deeplink ([#1181](https://github.com/MetaMask/metamask-sdk/pull/1181))
- refactor(sdk): always send RPC requests via network and deeplink ([#1181](https://github.com/MetaMask/metamask-sdk/pull/1181))
=> Release 107.0.0

package.json, packages/sdk-install-modal-web/CHANGELOG.md, packages/sdk-install-modal-web/package.json, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk/CHANGELOG.md, packages/sdk/package.json
- feat: improves the react connected hook when using extension & emit terminate when using extension ([#1186](https://github.com/MetaMask/metamask-sdk/pull/1186))
- chore: add analytics to install modal ([#1189](https://github.com/MetaMask/metamask-sdk/pull/1189))
- feat: add MetaMask Flask provider support for EIP-6963 ([#1192](https://github.com/MetaMask/metamask-sdk/pull/1192))
- chore: call getPermissions on accountsChanged when using extension ([#1185](https://github.com/MetaMask/metamask-sdk/pull/1185))
- Fix nextjs localstorage issue ([#1193](https://github.com/MetaMask/metamask-sdk/pull/1193))
- fix(MetaMaskInstaller): replace delete with assignment to undefined for window.ethereum ([#1162](https://github.com/MetaMask/metamask-sdk/pull/1162))
- feat: improves the react connected …
=> Release 108.0.0

package.json, packages/sdk-install-modal-web/CHANGELOG.md, packages/sdk-install-modal-web/package.json, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk/CHANGELOG.md, packages/sdk/package.json
- fix: Fix analytics for unwanted events when using extension ([#1219](https://github.com/MetaMask/metamask-sdk/pull/1219))
- chore: updates assets ([#1220](https://github.com/MetaMask/metamask-sdk/pull/1220))
- fix: Fix analytics for unwanted events when using extension ([#1219](https://github.com/MetaMask/metamask-sdk/pull/1219))
=> Release 110.0.0

package.json, packages/sdk-install-modal-web/CHANGELOG.md, packages/sdk-install-modal-web/package.json, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk/CHANGELOG.md, packages/sdk/package.json
Reverts MetaMask/metamask-sdk#1221
=> Revert "Release 110.0.0"

.github/workflows/publish-release.yml
=> fix: uploads all dists on build

.github/workflows/publish-release.yml
=> fix: fixes the upload paths for artifacts

.github/workflows/publish-release.yml
- Adds missing publishing token
=> ci: adds publishing token

.github/workflows/publish-release.yml
Adds `action-publish-release` to the publish workflow.
=> feat: adds action-publish-release to publish workflow

packages/sdk-socket-server-next/src/analytics-api.ts
This PR does a few of things
* Increases the `slotsRefreshTimeout` to 5 seconds, to allow more time to refresh large slot cache changes
* Decreases the `slotsRefreshInterval` to 2 seconds, to ensure we are always using the most up-to-date slot cache
* Adds a call to `refreshSlotsCache()` (when in cluster mode) to `reconnectOnError` and in the `ready` event to ensure we are always using the most up-to-date slot cache
=> fix(redis): increase slotsRefresh{timeout|interval} and add refreshSlotsCache

packages/sdk-socket-server-next/src/analytics-api.ts
This PR disables auto pipelining in `ioredis` to avoid pipeline related errors when we get `MOVED` errors.
=> Disable auto pipelining in ioredis

packages/sdk-socket-server-next/src/analytics-api.ts
This reverts commit 1511dc011faede6481e7e2200d23a1cf3c02ec11.
=> Revert "chore(redis): disable auto pipelining"

scripts/deploy-cdn.sh
Fixes the deploy path for CDN through GH pages.
=> chore: fixes the CDN deploy path

packages/sdk-socket-server-next/src/analytics-api.ts
Fixes filter logic for analytics filter from #1249
=> fix(analytics): fix filter to check body.method

packages/sdk-socket-server-next/src/metrics.ts, packages/sdk-socket-server-next/src/socket-config.ts
=> Add more metrics

packages/sdk-socket-server-next/src/protocol/handleJoinChannel.ts
=> dirty-improve

packages/sdk-socket-server-next/src/protocol/handleJoinChannel.ts, packages/sdk-socket-server-next/src/socket-config.ts
=> better metrics

packages/playground-next/src/app/page.tsx
Adds personal signature functionality to the Next.js playground Home component.
- Added state for managing signature and loading status
- Implemented `handlePersonalSign` function to request signatures from connected wallets
- Added UI button to trigger signing and display the resulting signature
- Updated disconnect flow to clear signature state
Connect wallet → Click "Personal Sign" → Approve in wallet → Verify signature display
=> feat: add personal sign functionality to next playground

package.json, yarn.lock
Bumps the version of create-release-branch to latest @4.1.2
=> chore: bumps the version of create-release-branch

package.json, yarn.lock
Reverts MetaMask/metamask-sdk#1275
=> Revert "chore: bumps the version of create-release-branch"

packages/sdk-analytics/package.json
Simple changes, making the sdk-analytics package public
=> fix: make the package public

packages/sdk-analytics/CHANGELOG.md, packages/sdk-analytics/package.json, packages/sdk-analytics/src/index.ts, yarn.lock
* Removing the private: false attribute from package json.
* Apply linting fixes
* Add missing script to sdk-analytics lint:changelog (required by CI) 
* Add missing dev dependency to sdk-analytics
=> fix: correct sdk analytics lint issued and package scope fix

package.json, packages/sdk-analytics/CHANGELOG.md, packages/sdk-analytics/package.json
- Add New Analytics Client ([#1270](https://github.com/MetaMask/metamask-sdk/pull/1270))
- fix: correct sdk analytics lint issued and package scope fix ([#1281](https://github.com/MetaMask/metamask-sdk/pull/1281))
- fix: make the package public ([#1279](https://github.com/MetaMask/metamask-sdk/pull/1279))
=> Release 111.0.0
