packages/sdk-communication-layer/package.json
packages/sdk-communication-layer/src/KeyExchange.ts
packages/sdk-install-modal-web/src/components/AdvantagesListItem.tsx

- Fix an issue with backward compatibility on Android making the app going back by itself.
- Fix a css issue from https://github.com/MetaMask/metamask-sdk/issues/72

[FIX] sdk backward compatibility issue

---

packages/examples/create-react-app/sdk-copy.sh
packages/sdk-communication-layer/package.json
packages/sdk-communication-layer/src/KeyExchange.ts
packages/sdk-communication-layer/src/SocketService.ts
packages/sdk/package.json

- bump sdk version
- bump comm layer version
- fix hanging keyexchange (both side waiting each other) on newest sdk connecting to older metamask

[FIX] hanging keyexchange mm63

---

packages/devreactnative/package.json
packages/examples/nodejs/index.js
packages/examples/nodejs/package.json
packages/sdk/src/sdk.ts
packages/sdk/src/services/RemoteConnection.ts
packages/sdk/src/ui/InstallModal/pendingModal-nodejs.ts

- Provide developer with the ability to customize all the modal windows that are displayed (eg: i18n)
- Solves https://github.com/MetaMask/metamask-sdk/issues/87
- Add example of customization for nodejs project
```js
const sdk = new MetaMaskSDK({
shouldShimWeb3: false,
storage: {
enabled: true,
},
modals: {
install: ({ link }) => {
// console.debug(`open link ${link}`);
qrcode.generate(link, { small: true }, (qr) => console.log(qr));
},
otp: () => {
return {
updateOTPValue: (otpValue) => {
if (otpValue !== '') {
console.debug(
`[CUSTOMIZE TEXT] Choose the following value on your metamask mobile wallet: ${otpValue}`,
);
}
},
}
}
},
});
```

[FEAT] Allow modal customisation 

---

packages/sdk-communication-layer/src/SocketService.ts

With session persistence, we need to ignore the PAUSED status as the wallet may be killed after being paused.
When restarting, it would generate new encryption key pair that would be ignored by the dapp.
The best way is to always reset key exchange status everytime wallet is disconnected.

[FEAT] reconnect after pause kill

---

.github/workflows/publish-preview.yml

The publish preview build job was building the project twice. Now it will only build once.

Prevent duplicate preview build

---

package.json

The root build command was only building the communication layer and install web modal packages. Now it will build all packages.
The verbose flag has been added as well, so that we get more informative logs from the build process.

Fix root build command

---

packages/sdk/package.json

Updating to 0.3.0 makes TypeScript fail because it can't find the type defs.

Fix types path

---

packages/sdk/src/utils/suffixCheck.ts

Fix `TypeError: Cannot read property 'pathname' of undefined` error in RN

Skip suffix check if location does not exist

---

packages/sdk-communication-layer/src/RemoteCommunication.ts
packages/sdk-communication-layer/src/config.ts

Currently, communication layer was waiting for 'ready' message from the wallet to send rpc requests.
This is incorrect since ready only means the key exchange has been completed (not that the connection was authorized or otp completed).
With this new feature, rpc methods won't be send to wallet until connection is authorized and validated on the wallet and thus prevent errors in the console.

[FEAT] wait for authorized event

---

package.json
packages/sdk-communication-layer/CHANGELOG.md
packages/sdk-communication-layer/package.json
packages/sdk-communication-layer/src/RemoteCommunication.ts
packages/sdk-communication-layer/src/SocketService.ts
packages/sdk/CHANGELOG.md
packages/sdk/package.json

- Release sdk 0.4.0
- Release sdk-communication-layer 0.4.0
Changelog:
- fix: invalid types path ([#173](https://github.com/MetaMask/metamask-sdk/pull/173))
- fix(sdk): react native detection ([#174](https://github.com/MetaMask/metamask-sdk/pull/174))
- feat: linter improvements ([#175](https://github.com/MetaMask/metamask-sdk/pull/175))
- [FEAT] authorized improvements + typings ([#158](https://github.com/MetaMask/metamask-sdk/pull/158))

Release 8.0.0

---

packages/sdk/src/sdk.ts

add `extensionOnly` sdk option parameter to let user directly use the extension (NOT RECOMMENDED).

feat: options to use metamask browser extension only (skip modal)

---

package.json
packages/sdk-communication-layer/CHANGELOG.md
packages/sdk-communication-layer/package.json
packages/sdk/CHANGELOG.md
packages/sdk/package.json
packages/sdk/src/sdk.ts

- feat: remove webrtc references ([#227](https://github.com/MetaMask/metamask-sdk/pull/227))
- refactor: simplify connection flow ([#226](https://github.com/MetaMask/metamask-sdk/pull/226))
- feat: cleanup obsolete walletconnect references ([#223](https://github.com/MetaMask/metamask-sdk/pull/223))
- fix: initial connection promise potentially dangling with browser extension ([#218](https://github.com/MetaMask/metamask-sdk/pull/218))
- feat: persist extension provider preferences
- feat: remove webrtc references ([#227](https://github.com/MetaMask/metamask-sdk/pull/227))
- refactor: simplify connection flow ([#226](https://github.com/MetaMask/metamask-sdk/pull/226))
- feat: cleanup obsolete walletconnect references ([#223](https://github.com/MetaMask/metamask-sdk/pull/223))
- feat: …

Release 14.0.0

---

package.json
packages/sdk-react/CHANGELOG.md
packages/sdk-react/package.json
packages/sdk/CHANGELOG.md
packages/sdk/package.json
packages/sdk/src/sdk.ts
packages/sdk/src/storage-manager/getStorageManager.ts

- feat: monorepo examples integration ([#239](https://github.com/MetaMask/metamask-sdk/pull/239))
- fix: sdk hook connector error with strictmode ([#234](https://github.com/MetaMask/metamask-sdk/pull/234))
- feat: monorepo examples integration ([#239](https://github.com/MetaMask/metamask-sdk/pull/239))
- feat: check init before connect (+dynamic platform import) ([#238](https://github.com/MetaMask/metamask-sdk/pull/238))
- fix: sdk hook connector error with strictmode ([#234](https://github.com/MetaMask/metamask-sdk/pull/234))
- fix: autoconnection setting ([#235](https://github.com/MetaMask/metamask-sdk/pull/235))
- fix: invalid types during build pipeline ([#233](https://github.com/MetaMask/metamask-sdk/pull/233))

Release 16.0.0

---

packages/devnext/src/pages/_app.tsx
packages/sdk/src/Platform/PlatfformManager.ts
packages/sdk/src/sdk.ts

Disable auto connect feature on mobile because it doesn't make sense to automatically tries to deeplink and gives an inconsistent ux between platforms.

feat: restrict autoconnect desktopweb

---

packages/deve2e/package.json
packages/deve2e/tsconfig.json
yarn.lock

feat: add pathmapping to deve2e nodejs project
This allows faster development without recompiling dependencies on each run.

feat: add pathmapping to deve2e nodejs project

---

packages/sdk/package.json

Without "sideEffects" defined (e.g. "sideEffects": false) build systems aren't able to properly eliminate dead code (e.g. Next.js) and could still load these packages even if they are not used.
More info: https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free

feat: add sideEffects field to sdk package

---

packages/sdk-communication-layer/src/RemoteCommunication.test.ts
packages/sdk-communication-layer/src/services/RemoteCommunication/ChannelManager/clean.test.ts
packages/sdk-communication-layer/src/services/RemoteCommunication/ChannelManager/generateChannelIdConnect.test.ts
packages/sdk-communication-layer/src/services/RemoteCommunication/ConnectionManager/connectToChannel.test.ts
packages/sdk-communication-layer/src/services/RemoteCommunication/ConnectionManager/disconnect.test.ts
packages/sdk-communication-layer/src/services/RemoteCommunication/ConnectionManager/handleAuthorization.test.ts
packages/sdk-communication-layer/src/services/RemoteCommunication/ConnectionManager/initCommunicationLayer.test.ts
packages/sdk-communication-layer/src/services/RemoteCommunication/ConnectionManager/originatorSessionConnect.test.ts
packages/sdk-communication-layer/src/services/RemoteCommunication/ConnectionManager/resume.test.ts
packages/sdk-communication-layer/src/services/RemoteCommunication/EventListeners/handleAuthorizedEvent.test.ts
packages/sdk-communication-layer/src/services/RemoteCommunication/EventListeners/handleChannelCreatedEvent.test.ts
packages/sdk-communication-layer/src/services/RemoteCommunication/EventListeners/handleClientsConnectedEvent.test.ts
packages/sdk-communication-layer/src/services/RemoteCommunication/EventListeners/handleClientsDisconnectedEvent.test.ts
packages/sdk-communication-layer/src/services/RemoteCommunication/EventListeners/handleClientsWaitingEvent.test.ts
packages/sdk-communication-layer/src/services/RemoteCommunication/EventListeners/handleKeysExchangedEvent.test.ts
packages/sdk-communication-layer/src/services/RemoteCommunication/EventListeners/handleMessageEvent.test.ts
packages/sdk-communication-layer/src/services/RemoteCommunication/EventListeners/handleSocketDisconnectedEvent.test.ts
packages/sdk-communication-layer/src/services/RemoteCommunication/EventListeners/handleSocketReconnectEvent.test.ts
packages/sdk-communication-layer/src/services/RemoteCommunication/MessageHandlers/handleAuthorizedMessage.test.ts
packages/sdk-communication-layer/src/services/RemoteCommunication/MessageHandlers/handleOriginatorInfoMessage.test.ts
packages/sdk-communication-layer/src/services/RemoteCommunication/MessageHandlers/handleOtpMessage.test.ts
packages/sdk-communication-layer/src/services/RemoteCommunication/MessageHandlers/handlePauseMessage.test.ts
packages/sdk-communication-layer/src/services/RemoteCommunication/MessageHandlers/handleReadyMessage.test.ts
packages/sdk-communication-layer/src/services/RemoteCommunication/MessageHandlers/handleTerminateMessage.test.ts
packages/sdk-communication-layer/src/services/RemoteCommunication/MessageHandlers/handleWalletInfoMessage.test.ts
packages/sdk-communication-layer/src/services/RemoteCommunication/MessageHandlers/onCommunicationLayerMessage.test.ts
packages/sdk-communication-layer/src/services/RemoteCommunication/MessageHandlers/sendMessage.test.ts
packages/sdk-communication-layer/src/services/RemoteCommunication/StateManger/setLastActiveDate.test.ts
packages/sdk-communication-layer/src/services/RemoteCommunication/StorageManager/testStorage.test.ts

This PR introduces unit tests for the RemoteCommunication class to ensure the stability and reliability of its methods and behaviors.
By adding these tests, we aim to catch potential issues and maintain the robustness of the SocketService functionalities.
That's the coverage results:

feat: add unit tests to the RemoteCommunication class

---

packages/sdk-socket-server/api-config.js

Fixes issues when sending properties with potential long content like 'icon'

feat: prevent sending icon to segment

---

package.json
packages/sdk-communication-layer/CHANGELOG.md
packages/sdk-communication-layer/package.json
packages/sdk-react-ui/CHANGELOG.md
packages/sdk-react-ui/README.md
packages/sdk-react-ui/package.json
packages/sdk-react/CHANGELOG.md
packages/sdk-react/package.json
packages/sdk/CHANGELOG.md
packages/sdk/package.json
yarn.lock

Release 20.0.1

---

package.json
packages/sdk-communication-layer/CHANGELOG.md
packages/sdk-communication-layer/package.json
packages/sdk-react-ui/CHANGELOG.md
packages/sdk-react-ui/README.md
packages/sdk-react-ui/package.json
packages/sdk-react/CHANGELOG.md
packages/sdk-react/package.json
packages/sdk/CHANGELOG.md
packages/sdk/package.json
yarn.lock

Release 20.0.0

---

package.json
packages/sdk-communication-layer/CHANGELOG.md
packages/sdk-communication-layer/package.json
packages/sdk-install-modal-web/CHANGELOG.md
packages/sdk-install-modal-web/package.json
packages/sdk-react-ui/CHANGELOG.md
packages/sdk-react-ui/package.json
packages/sdk-react/CHANGELOG.md
packages/sdk-react/package.json
packages/sdk/CHANGELOG.md
packages/sdk/package.json
packages/truffle/package.json

Release 21.0.0

---

package.json
packages/sdk-communication-layer/CHANGELOG.md
packages/sdk-communication-layer/package.json
packages/sdk-install-modal-web/CHANGELOG.md
packages/sdk-install-modal-web/package.json
packages/sdk-react-ui/CHANGELOG.md
packages/sdk-react-ui/package.json
packages/sdk-react/package.json
packages/sdk/CHANGELOG.md
packages/sdk/package.json

feat: release 23.0.0

---

package.json
packages/sdk-communication-layer/CHANGELOG.md
packages/sdk-communication-layer/package.json
packages/sdk-install-modal-web/CHANGELOG.md
packages/sdk-install-modal-web/package.json
packages/sdk-react-ui/CHANGELOG.md
packages/sdk-react-ui/package.json
packages/sdk-react/package.json
packages/sdk/CHANGELOG.md
packages/sdk/package.json

Release 23.0.0

---

packages/sdk/src/services/SDKProvider/InitializationManager/initializeStateAsync.ts

This PR aims to fix an issue where properties of **SDKProvider**, such as `this.debug`, were not initialized before `_initializeStateAsync` was invoked. This led to unexpected behavior and potential bugs in the application logic. 
Furthermore, this issue existed even before the recent refactor after investigation, but it was hidden because `this.debug` didn't throw a JS error.
Issue:
When `_initializeStateAsync` is invoked, properties like `this.debug` are still `undefined`. This suggests that the method is called before the class is fully initialized. The likely indicted is the parent class `AbstractStreamProvider`, which appears to invoke this method prematurely. This behavior was observed even before the recent code refactor.
Workaround:
To remedy this, the PR adds a check within …

fix: initialize state in _initializeStateAsync to address uninitialized properties issue

---

packages/devnext/src/pages/index.tsx
packages/sdk-install-modal-web/src/ModalLoader.tsx
packages/sdk-install-modal-web/src/SelectModal.tsx
packages/sdk/src/services/MetaMaskSDK/ConnectionManager/terminate.ts
packages/sdk/src/services/MetaMaskSDK/ProviderManager/connectWithExtensionProvider.ts
packages/sdk/src/services/RemoteConnection/ConnectionManager/connectWithModalInstaller.ts
packages/sdk/src/services/RemoteConnection/ConnectionManager/startConnection.ts
packages/sdk/src/services/RemoteConnection/ModalManager/reconnectWithModalOTP.ts
packages/sdk/src/services/RemoteConnection/ModalManager/showInstallModal.ts
packages/sdk/src/services/RemoteConnection/RemoteConnection.ts
packages/sdk/src/services/SDKProvider/ConnectionManager/handleDisconnect.ts
packages/sdk/src/ui/InstallModal/InstallModal-web.ts
packages/sdk/src/ui/InstallModal/pendingModal-web.ts

- improve logging details
- prevent re-initializing the sdk on connection termination (especially useful when integrating with external provider: web3-onboard)
- fix: issue when the modals were not properly displaying after connection is terminated after switching provider.

fix: edge case when modal not fully resetting after termination

---

package.json
packages/sdk-communication-layer/CHANGELOG.md
packages/sdk-communication-layer/package.json
packages/sdk-install-modal-web/CHANGELOG.md
packages/sdk-install-modal-web/package.json
packages/sdk-react-ui/CHANGELOG.md
packages/sdk-react-ui/package.json
packages/sdk-react/CHANGELOG.md
packages/sdk-react/package.json
packages/sdk/CHANGELOG.md
packages/sdk/package.json
packages/sdk/src/services/MobilePortStream/onMessage.test.ts
packages/sdk/src/services/MobilePortStream/onMessage.ts
packages/sdk/src/services/MobilePortStream/write.test.ts
packages/sdk/src/services/MobilePortStream/write.ts
packages/sdk/src/services/RemoteCommunicationPostMessageStream/extractMethod.ts
packages/sdk/src/services/RemoteCommunicationPostMessageStream/onMessage.ts

- feat: add unit tests to the RemoteCommunicationPostMessageStream class ([#337](https://github.com/MetaMask/metamask-sdk/pull/337))
- feat: refactor the RemoteCommunicationPostMessage stream class ([#336](https://github.com/MetaMask/metamask-sdk/pull/336))
- feat: add unit tests to the MobilePortStream class ([#335](https://github.com/MetaMask/metamask-sdk/pull/335))
- feat: add unit tests to the PlatformManager class ([#333](https://github.com/MetaMask/metamask-sdk/pull/333))
- feat: refactor the PlatformManager class ([#332](https://github.com/MetaMask/metamask-sdk/pull/332))
- fix: edge case when modal not fully resetting after termination ([#339](https://github.com/MetaMask/metamask-sdk/pull/339))
- fix: initialize state in _initializeStateAsync to address uninitialized properties …

Release 27.0.0

---

packages/examples/nextjs-demo/sdk-copy.sh
packages/examples/pure-javascript/sdk-copy.sh
packages/examples/vuejs/sdk-copy.sh
packages/sdk-communication-layer/jest.config.ts
packages/sdk-install-modal-web/src/ModalLoader.tsx
packages/sdk-install-modal-web/src/PendingModal.tsx
packages/sdk/jest.config.ts
packages/sdk/src/constants.ts
packages/sdk/src/services/RemoteConnection/ConnectionManager/startConnection.test.ts
packages/sdk/src/services/RemoteConnection/ConnectionManager/startConnection.ts
packages/sdk/src/services/RemoteConnection/ModalManager/reconnectWithModalOTP.test.ts
packages/sdk/src/services/RemoteConnection/ModalManager/reconnectWithModalOTP.ts
packages/sdk/src/services/RemoteConnection/ModalManager/showInstallModal.test.ts
packages/sdk/src/services/RemoteConnection/RemoteConnection.ts
packages/sdk/src/services/SDKProvider/ConnectionManager/handleDisconnect.test.ts
packages/sdk/src/ui/InstallModal/pendingModal-web.ts

Extended the session persistence time to one hour without showing OTP.
For the first hour after connecting, the session will remain active without requesting an OTP.
The following tests are conducted to ensure that everything is working properly:
Apps tested include:
All of the apps tested on IOS and Android with a new wallet build that includes the new OTP changes.
The cases that have been checked were when the channel was active recently and when the channel was NOT active recently in order to test both flows.
Everything appears to be working as expected.

feat: extend the time we resume the session without showing OTP

---

packages/sdk-communication-layer/src/RemoteCommunication.ts

Fix issue that dApp would send `sdk_connect_request_started_mobile` instead of `sdk_connect_request`.

fix: sdk connection request event

---

.github/ISSUE_TEMPLATE/bug_report.yaml
packages/sdk/package.json
yarn.lock

Allow more recent version of react-native without issuing dependency warning.

feat: allow all react-native peer deps

---

package.json
packages/sdk-communication-layer/CHANGELOG.md
packages/sdk-communication-layer/package.json
packages/sdk/CHANGELOG.md
packages/sdk/package.json
packages/sdk/src/config.ts

- feat: allow all react-native peer deps ([#366](https://github.com/MetaMask/metamask-sdk/pull/366))
- fix: sdk connection request event ([#364](https://github.com/MetaMask/metamask-sdk/pull/364))
- feat: wrap eth_accounts when disconnected to allow read only / offline calls ([#363](https://github.com/MetaMask/metamask-sdk/pull/363))
- fix: sdk connection request event ([#364](https://github.com/MetaMask/metamask-sdk/pull/364))

Release 29.0.0

---

packages/sdk-react/src/MetaMaskProvider.tsx

Previously, switching to extension wouldn't automatically adjust the value of the account and chainId when using sdk-react.
This PR allows always updating values to current selected provider.

feat: update account and chain values in sdk hook on extension

---

packages/devnext/src/pages/index.tsx
packages/sdk/src/config.ts
packages/sdk/src/provider/initializeMobileProvider.ts

This allow the client to work while wallet is disconnected and the address cached values are automatically updated as soon as the wallet is back online.

feat: cache selected account and selected chain

---

packages/sdk-install-modal-web/src/ModalLoader.tsx
packages/sdk/src/services/RemoteConnection/EventListeners/setupListeners.ts

- Fix the modal query selection when the pendingContainer is non existant which allow to always displays OTP value.
- Cleanup modal when user click outside the action button on the wallet ( previously it would keep the connection open ).
Fixes https://github.com/MetaMask/metamask-sdk/issues/327

fix: modal cleanup and otp selection

---

packages/sdk/src/sdk.test.ts
packages/sdk/src/sdk.ts

Prevent user from using sdk.disconnect() which is now deprecated in favor of terminate().

feat: alias terminate to disconnect on sdk

---

README.md
package.json
packages/sdk-communication-layer/CHANGELOG.md
packages/sdk-communication-layer/package.json
packages/sdk-install-modal-web/CHANGELOG.md
packages/sdk-install-modal-web/package.json
packages/sdk-install-modal-web/src/ModalLoader.tsx
packages/sdk-react-ui/CHANGELOG.md
packages/sdk-react-ui/package.json
packages/sdk-react/CHANGELOG.md
packages/sdk-react/package.json
packages/sdk/CHANGELOG.md
packages/sdk/package.json
packages/sdk/src/sdk.ts

- feat: add sdk version and change modal order ([#405](https://github.com/MetaMask/metamask-sdk/pull/405))
- feat: implementing internationalization via i18next package ([#403](https://github.com/MetaMask/metamask-sdk/pull/403))
- feat: alias terminate to disconnect on sdk ([#399](https://github.com/MetaMask/metamask-sdk/pull/399))
- fix typos ([#401](https://github.com/MetaMask/metamask-sdk/pull/401))
- fix: modal cleanup and otp selection ([#402](https://github.com/MetaMask/metamask-sdk/pull/402))
- fix typos ([#401](https://github.com/MetaMask/metamask-sdk/pull/401))
- feat: add sdk version and change modal order ([#405](https://github.com/MetaMask/metamask-sdk/pull/405))
- feat: implementing internationalization via i18next package …

Release 31.0.0

---

packages/sdk-communication-layer/src/KeyExchange.ts
packages/sdk-communication-layer/src/services/SocketService/EventListeners/handleMessage.ts

Sometime the keyExchange status can be into an incorrect state (usually due to metamask being killed while connection is paused --> there is no way to detect this edge case), the connection gets restored but it can lead to a missing rpc call.
This PR fixes the above described rare edge case.

feat: connection recovery edge case

---

package.json
packages/sdk-communication-layer/CHANGELOG.md
packages/sdk-communication-layer/package.json
packages/sdk-communication-layer/src/services/SocketService/EventListeners/handleMessage.test.ts
packages/sdk-communication-layer/src/services/SocketService/EventListeners/handleMessage.ts
packages/sdk-install-modal-web/CHANGELOG.md
packages/sdk-install-modal-web/package.json
packages/sdk-react-ui/CHANGELOG.md
packages/sdk-react-ui/package.json
packages/sdk-react/CHANGELOG.md
packages/sdk-react/package.json
packages/sdk/CHANGELOG.md
packages/sdk/package.json
packages/sdk/rollup.config.js

- feat: connectAndSign feature ([#410](https://github.com/MetaMask/metamask-sdk/pull/410))
- feat: connection recovery edge case ([#411](https://github.com/MetaMask/metamask-sdk/pull/411))
- fix: balance only display when debug is set ([#408](https://github.com/MetaMask/metamask-sdk/pull/408))
- feat: add unit tests to the sdk-react package ([#369](https://github.com/MetaMask/metamask-sdk/pull/369))

Release 32.0.0

---

packages/sdk-communication-layer/src/types/TrackingEvent.ts
packages/sdk/src/services/MetaMaskSDK/InitializerManager/handleAutoAndExtensionConnections.ts

Send `sdk_extension_utilized` analytics event whenever extension is selected from a cached choice.

feat: send sdk_extension_utilized analytics event when extension is selected from cached choice.

---

packages/sdk-react-ui/tailwind.config.js

Prevent tailwind css preflight to reset overall styles that can be conflicting with dapps styles.

fix: flightwind css leaking with preflight

---

packages/sdk/src/constants.ts
packages/sdk/src/services/MetaMaskSDK/InitializerManager/performSDKInitialization.test.ts
packages/sdk/src/services/MetaMaskSDK/InitializerManager/setupExtensionPreferences.ts
packages/sdk/src/utils/eip6963RequestProvider.test.ts
packages/sdk/src/utils/eip6963RequestProvider.ts
packages/sdk/src/utils/get-browser-extension.test.ts
packages/sdk/src/utils/get-browser-extension.ts
packages/sdk/src/utils/shouldInjectProvider.ts

This Pull Request introduces support to the EIP-6963 protocol, enhancing our capability to interact with Ethereum browser extensions, particularly with MetaMask.
**Main Changes:**
`eip6963RequestProvider` Function: This function is designed to send a request event and await for an announcement of a provider, (To the MetaMask provider). If a valid provider responds within the given timeout, it will be returned,
The `eip6963RequestProvider` function is used in the `getBrowserExtension` function, and if it does not return a provider it will fall back to the old logic of `window.ethereum`.
**Benefits:**
- Provides a consistent and streamlined way to detect and utilize the MetaMask browser extension provider.
- Offers a fallback mechanism to ensure functionality even if the primary method …

feat: add support to EIP-6963 protocol

---

packages/sdk/src/services/RemoteCommunicationPostMessageStream/write.test.ts
packages/sdk/src/services/RemoteCommunicationPostMessageStream/write.ts

Allow to detect the origin as qrcode on the wallet to prevent scanning using a photo app and metamask thinking it is a deeplink

feat: detect qrcode origin on wallet

---

package.json
packages/sdk-communication-layer/CHANGELOG.md
packages/sdk-communication-layer/package.json
packages/sdk-install-modal-web/CHANGELOG.md
packages/sdk-install-modal-web/package.json
packages/sdk-react-ui/CHANGELOG.md
packages/sdk-react-ui/package.json
packages/sdk-react/CHANGELOG.md
packages/sdk-react/package.json
packages/sdk/CHANGELOG.md
packages/sdk/package.json

- feat: rename metamask_chainRPCs to metamask_batch and add unit tests ([#440](https://github.com/MetaMask/metamask-sdk/pull/440))
- fix: add metadata to the sdk_extension_utilized analytics event ([#433](https://github.com/MetaMask/metamask-sdk/pull/433))
- feat: chaining of rpc calls ([#434](https://github.com/MetaMask/metamask-sdk/pull/434))
- feat: add support to EIP-6963 protocol ([#423](https://github.com/MetaMask/metamask-sdk/pull/423))
- feat: rename metamask_chainRPCs to metamask_batch and add unit tests ([#440](https://github.com/MetaMask/metamask-sdk/pull/440))
- feat: rename metamask_chainRPCs to metamask_batch and add unit tests ([#440](https://github.com/MetaMask/metamask-sdk/pull/440))
- fix: account balance not updating when chain changes …

Release 34.0.0

---

packages/devnext/next.config.js
packages/sdk-communication-layer/rollup.config.js
packages/sdk/bundle_stats/browser-es-stats-0.11.0.html
packages/sdk/bundle_stats/browser-umd-iife-stats-0.11.0.html
packages/sdk/bundle_stats/node-stats-0.11.0.html
packages/sdk/bundle_stats/react-native-stats-0.11.0.html
packages/sdk/package.json
packages/sdk/rollup.config.js
packages/sdk/src/types/globals.d.ts
packages/sdk/src/ui/InstallModal/InstallModal-nodejs.test.ts
packages/sdk/src/ui/InstallModal/InstallModal-nodejs.ts
yarn.lock

Allow the package to work with nodejs strictmode.
I had to fork / republish the qrcode-terminal dependency and remove all the legacy octal that were not permitted in strictmode.
- Add visualizer to keep track of bundle history

build: improve sdk bundle to work with nodejs strictmode

---

packages/sdk-react-ui/src/MetaMaskUIProvider.tsx

Make sure the list of valid connectors update with changing chains and connectors.

fix: add missing wagmi provider wrapper dependencies

---

package.json
packages/sdk-react-ui/CHANGELOG.md
packages/sdk-react-ui/package.json
packages/sdk-react/CHANGELOG.md
packages/sdk-react/package.json
packages/sdk/CHANGELOG.md
packages/sdk/package.json

- fix: add missing wagmi provider wrapper dependencies ([#459](https://github.com/MetaMask/metamask-sdk/pull/459))

Release 36.0.0

---

packages/sdk-communication-layer/src/services/RemoteCommunication/ConnectionManager/initCommunicationLayer.ts

Disable sending favicon as base64 because it is slower to encrypt on some device as well as inefficient during limited connection exchange between devices.
Instead the dapp should set the url in the metadata and the wallet will extract the favicon from the url.

feat: disable favicon in dappmetadata

---

packages/devreactnative/App.tsx
packages/sdk/src/services/PlatfformManager/openDeeplink.ts

When using sdk with a custom url opening function `openDeeplink option`, it would only send the universal link url as parameter.
```ts
const sdk = new MetaMaskSDK({
openDeeplink: (link: string, target?: string) => {
console.debug(`App::openDeepLink() ${link}`);
if (canOpenLink) {
Linking.openURL(link);
} else {
console.debug(
'useBlockchainProiver::openDeepLink app is not active - skip link',
link,
);
}
},
```
With this PR, the value of the link will be dynamic based on the sdk `useDeeplink` option.

feat: sdk option openDeepLink with dynamic url 

---

packages/sdk/src/sdk.ts
packages/sdk/src/services/RemoteCommunicationPostMessageStream/write.test.ts
packages/sdk/src/services/RemoteCommunicationPostMessageStream/write.ts
packages/sdk/src/services/RemoteConnection/ConnectionManager/startConnection.ts
packages/sdk/src/services/RemoteConnection/ModalManager/showActiveModal.test.ts
packages/sdk/src/services/RemoteConnection/ModalManager/showActiveModal.ts
packages/sdk/src/services/RemoteConnection/RemoteConnection.test.ts
packages/sdk/src/services/RemoteConnection/RemoteConnection.ts

Previously, the QRCode url would only contain the universal link regardless of the initialization preferences since it doesn't open an actual deeplink. This can lead to inconsistency on the wallet and thus better aligning the url with the actual deeplink schema.
- Allow switching between deeplink / universal link even when qrcode is selected.
- Add t={q|d} to differentiate on the wallet for the correct origin and prevent bypass when scanning from camera.

feat: qrcode deeplinks

---

packages/sdk-communication-layer/src/KeyExchange.test.ts
packages/sdk-communication-layer/src/KeyExchange.ts
packages/sdk-communication-layer/src/RemoteCommunication.ts
packages/sdk-communication-layer/src/SocketService.ts
packages/sdk-communication-layer/src/types/CommunicationLayer.ts

Because of the nature of session persistence where both side can update their public keys independently while disconnected, this mechanism allow to update the dapp public key on the wallet via a deeplink instead of re-creating a full key exchange on the network.

feat: allow editing otherpublickey for faster connection recovery

---

packages/sdk/src/services/MetaMaskSDK/InitializerManager/initializeI18next.ts

Set `      compatibilityJSON: 'v3', ` on i18n to avoid having to polyfills on react native.

feat: add backward v3 json compatibility on i18n

---

packages/sdk/src/config.ts
packages/sdk/src/sdk.ts
packages/sdk/src/services/MetaMaskSDK/InitializerManager/setupExtensionPreferences.ts

Some client seem to only connect on the main provider before switching to extension and thus would miss extension chain events. This PR consolidate all events onto the main provider to fix that issue.
- Expose the mobile provider directly from sdk

feat: propagate extension events

---

package.json
packages/sdk-communication-layer/CHANGELOG.md
packages/sdk-communication-layer/package.json
packages/sdk-install-modal-web/CHANGELOG.md
packages/sdk-install-modal-web/package.json
packages/sdk-react-ui/CHANGELOG.md
packages/sdk-react-ui/package.json
packages/sdk-react/CHANGELOG.md
packages/sdk-react/package.json
packages/sdk/CHANGELOG.md
packages/sdk/package.json

- feat: propagate extension events ([#493](https://github.com/MetaMask/metamask-sdk/pull/493))
- feat: metamask/sdk-ui initial setup ([#487](https://github.com/MetaMask/metamask-sdk/pull/487))
- feat: add backward v3 json compatibility on i18n ([#483](https://github.com/MetaMask/metamask-sdk/pull/483))

Release 38.0.0

---

package.json
packages/sdk-communication-layer/CHANGELOG.md
packages/sdk-communication-layer/package.json
packages/sdk-install-modal-web/CHANGELOG.md
packages/sdk-install-modal-web/package.json
packages/sdk-react-ui/CHANGELOG.md
packages/sdk-react-ui/package.json
packages/sdk-react/CHANGELOG.md
packages/sdk-react/package.json
packages/sdk/CHANGELOG.md
packages/sdk/package.json

- feat: propagate extension events ([#493](https://github.com/MetaMask/metamask-sdk/pull/493))
- feat: metamask/sdk-ui initial setup ([#487](https://github.com/MetaMask/metamask-sdk/pull/487))
- feat: add backward v3 json compatibility on i18n ([#483](https://github.com/MetaMask/metamask-sdk/pull/483))

feat: release 38.0.0

---

package.json
packages/sdk-communication-layer/CHANGELOG.md
packages/sdk-communication-layer/package.json
packages/sdk-install-modal-web/CHANGELOG.md
packages/sdk-install-modal-web/package.json
packages/sdk-lab/CHANGELOG.md
packages/sdk-lab/package.json
packages/sdk-react-ui/CHANGELOG.md
packages/sdk-react-ui/package.json
packages/sdk-react/CHANGELOG.md
packages/sdk-react/package.json
packages/sdk-ui/CHANGELOG.md
packages/sdk-ui/package.json
packages/sdk/CHANGELOG.md
packages/sdk/package.json

- feat: add the option to add iconUrl to the dappMetadata ([#511](https://github.com/MetaMask/metamask-sdk/pull/511))
- feat: optimize rollup builds ([#496](https://github.com/MetaMask/metamask-sdk/pull/496))
- feat: add the option to add iconUrl to the dappMetadata ([#511](https://github.com/MetaMask/metamask-sdk/pull/511))
- feat: optimize rollup builds ([#496](https://github.com/MetaMask/metamask-sdk/pull/496))
- feat: add processing state when computing balance ([#519](https://github.com/MetaMask/metamask-sdk/pull/519))
- feat: design system part2 ([#517](https://github.com/MetaMask/metamask-sdk/pull/517))
- feat: optimize rollup builds ([#496](https://github.com/MetaMask/metamask-sdk/pull/496))
- fix: linting changelog issue after updating scripts …

feat: release 39.0.0

---

package.json
packages/sdk-communication-layer/CHANGELOG.md
packages/sdk-react-ui/CHANGELOG.md
packages/sdk-react-ui/package.json
packages/sdk-react/CHANGELOG.md
packages/sdk-react/package.json
packages/sdk-ui/CHANGELOG.md
packages/sdk-ui/package.json
packages/sdk/CHANGELOG.md
packages/sdk/package.json

- Increase version for sdk-ui release
- feat: add debug and rn compatibility to config provider ([#532](https://github.com/MetaMask/metamask-sdk/pull/532))
- feat: publish sdk-ui ([#533](https://github.com/MetaMask/metamask-sdk/pull/533))
- feat: add debug and rn compatibility to config provider ([#532](https://github.com/MetaMask/metamask-sdk/pull/532))
- feat: publish sdk-ui ([#533](https://github.com/MetaMask/metamask-sdk/pull/533))
- Initial npm publication

Release 41.0.0

---

package.json
packages/sdk-communication-layer/CHANGELOG.md
packages/sdk-communication-layer/package.json
packages/sdk-install-modal-web/CHANGELOG.md
packages/sdk-install-modal-web/package.json
packages/sdk-lab/CHANGELOG.md
packages/sdk-lab/package.json
packages/sdk-react-ui/CHANGELOG.md
packages/sdk-react-ui/package.json
packages/sdk-react/CHANGELOG.md
packages/sdk-react/package.json
packages/sdk-ui/CHANGELOG.md
packages/sdk-ui/package.json
packages/sdk/CHANGELOG.md
packages/sdk/package.json

- feat: add sdk instance to window scope to prevent double init ([#546](https://github.com/MetaMask/metamask-sdk/pull/546))
- fix: transfer the extracted favicon to base64 format in setupDappMetadata ([#536](https://github.com/MetaMask/metamask-sdk/pull/536))
- fix: compatibility with storage UI and devreact ([#545](https://github.com/MetaMask/metamask-sdk/pull/545))
- fix: storage UI and devreact ([#545](https://github.com/MetaMask/metamask-sdk/pull/545))
- fix: storybook setup ([#547](https://github.com/MetaMask/metamask-sdk/pull/547))
- fix: storage UI and devreact ([#545](https://github.com/MetaMask/metamask-sdk/pull/545))

Release 42.0.0

---

packages/sdk/src/services/MetaMaskSDK/InitializerManager/setupDappMetadata.test.ts
packages/sdk/src/services/MetaMaskSDK/InitializerManager/setupDappMetadata.ts

Change favicon from `base64` format to `url` format.

chore: change favicon from base64 format to url

---

packages/sdk-react/src/EventsHandlers/useHandleInitializedEvent.test.tsx
packages/sdk-react/src/EventsHandlers/useHandleInitializedEvent.ts

Fix issue of account address resetting on `_initialized` event.
Issue was due to refactor on MetaMaskProvider that I tagged as:
```
// FIXME calling directly useHandleInitializedEvent skip the parameter of the event.
const onInitialized = useHandleInitializedEvent(eventHandlerProps);
```

feat: account reset issue on _init event

---

packages/devnext/src/components/layout.tsx
packages/devnext/src/pages/demo.tsx
packages/devnext/src/pages/index.tsx
packages/devnext/src/pages/uikit.tsx
packages/devnext/src/pages/web3onboard.tsx
packages/devnext/src/utils/sign-utils.ts
packages/devreact/src/App.tsx
packages/devreact/src/index.tsx
packages/sdk/src/config.ts
packages/sdk/src/provider/initializeMobileProvider.ts
packages/sdk/src/sdk.ts
packages/sdk/src/services/MetaMaskSDK/ConnectionManager/connectWith.test.ts
packages/sdk/src/services/MetaMaskSDK/ConnectionManager/connectWith.ts

Allow to establish connection to the wallet with any wrapped rpc call.
```
const connectWith = async ({
type,
}: {
type:
| 'PERSONAL_SIGN'
| 'ETH_SENDTRANSACTION'
| 'ETH_SIGNTYPEDDATA_V4'
| 'ETH_CHAINID';
}) => {
try {
setRpcError(null);
setRequesting(true);
setResponse('');
const sendTransactionRpc = {
method: 'eth_sendTransaction',
params: [
{
to: '0xA9FBbc6C2E49643F8B58Efc63ED0c1f4937A171E', // Required except during contract publications.
from: '0xMYACCOUNT', // must match user's active address.
value: '0x5AF3107A4000', // Only required to send ether to the recipient from the initiating external account.
},
],
};
const personalSignRpc = {
method: 'personal_sign',
params: ['hello world', '0xMYACCOUNT'],
};
const signTypeDatav4Rpc = {
method: 'eth_signTypedData_v4',
params: …
```

feat: new rpc call metamask_connectwith

---

package.json
packages/sdk-communication-layer/CHANGELOG.md
packages/sdk-communication-layer/package.json
packages/sdk-communication-layer/src/KeyExchange.ts
packages/sdk-install-modal-web/CHANGELOG.md
packages/sdk-lab/CHANGELOG.md
packages/sdk-lab/package.json
packages/sdk-react-ui/CHANGELOG.md
packages/sdk-react-ui/package.json
packages/sdk-react/CHANGELOG.md
packages/sdk-react/package.json
packages/sdk-ui/CHANGELOG.md
packages/sdk-ui/package.json
packages/sdk/CHANGELOG.md
packages/sdk/package.json

- feat: new rpc call metamask_connectwith ([#558](https://github.com/MetaMask/metamask-sdk/pull/558))
- chore: change favicon from base64 format to url ([#550](https://github.com/MetaMask/metamask-sdk/pull/550))
- feat: expo keyexchange status and track last rpc id ([#554](https://github.com/MetaMask/metamask-sdk/pull/554))
- feat: account reset issue on _init event ([#556](https://github.com/MetaMask/metamask-sdk/pull/556))
- feat: expose rpc history and keep track of last call ([#555](https://github.com/MetaMask/metamask-sdk/pull/555))
- fix: balance not updating on metamask button ([#553](https://github.com/MetaMask/metamask-sdk/pull/553))
- feat: more cross platforms ui components ([#557](https://github.com/MetaMask/metamask-sdk/pull/557))

Release 43.0.0

---

packages/sdk-communication-layer/src/KeyExchange.ts

Allow mobile to overwrite keyexchange at any point which can be useful when the keys are updated via deeplink.

feat: graceful warning instead of throwing keyexchange

---

packages/devnext/package.json
packages/devnext/src/components/layout.tsx
packages/devreactnative/App.tsx
packages/sdk-ui/src/components/floating-metamask-button/floating-metamask-button.tsx
packages/sdk-ui/src/components/gasprice-panel/gasprice-panel.stories.tsx
packages/sdk-ui/src/components/gasprice-panel/gasprice-panel.tsx
packages/sdk-ui/src/components/metamask-modal/metamask-modal.tsx
packages/sdk-ui/src/components/sdk-config-card/sdk-config-card.tsx
packages/sdk-ui/src/components/sdk-summary/sdk-summary.tsx
packages/sdk-ui/src/components/swap-panel/swap-panel.stories.tsx
packages/sdk-ui/src/components/swap-panel/swap-panel.tsx
packages/sdk-ui/src/mocks/storybook.mocks.tsx
packages/sdk/src/config.ts
yarn.lock

New component inside the floating MetaMask Button to directly create swap from any dapps.
- Also allow to onboard users to onramp and buy currency
- [TESTING] new rpc call `metamask_open` which can be used to directly open a screen in the wallet

feat: ui quick swap and new rpc call metamask_open

---

packages/sdk-ui/src/constants/urls.ts

Update consensys.net url to consensys.io
https://github.com/Consensys/dx-team/issues/1703

consensys.net -> consensys.io

---

packages/sdk/src/services/MetaMaskSDK/InitializerManager/setupExtensionPreferences.ts

This PR optimizes the `setupExtensionPreferences` method by invoking `getMobileProvider` only if a mobile provider is detected. This is determined by checking the existence of `sdkProvider` in the instance. 
This conditional execution prevents unnecessary method calls, streamlining the setup process for extension preferences when a mobile provider is available.
Also that's going to fix this issue on Wagmi:
https://github.com/wevm/wagmi/issues/3400
- feat: Conditionally Invoke getMobileProvider in setupExtensionPreferences Based on if Mobile Provider is Availabile

feat: Conditionally Invoke getMobileProvider in setupExtensionPreferences Based on if Mobile Provider is Availabile

---

packages/sdk-communication-layer/rollup.config.js
packages/sdk-install-modal-web/rollup.config.js
packages/sdk-react-ui/rollup.config.js
packages/sdk-react/rollup.config.js
packages/sdk/rollup.config.js

Prevent excessive bundle size which included sourcemaps.
https://github.com/MetaMask/metamask-sdk/issues/628

feat: disable sourcemaps

---

packages/sdk-react/src/MetaMaskProvider.spec.tsx
packages/sdk-react/src/MetaMaskProvider.tsx
packages/sdk-react/src/SDKConfigProvider.tsx
packages/sdk-ui/src/components/sdk-status/sdk-status.tsx
packages/sdk/src/sdk.ts

Some of the sdk playground components require displaying channelId, previous method involved accessing values via theorically private methods.
Exposing the channelId directly is cleaner and simplify the code.
```ts
sdk.getChannelId() 
sdk.getWalletStatus()
const {  channelId } = useSDK();
```
Possible status:
```ts
export enum ConnectionStatus {
// DISCONNECTED: counterparty is disconnected
DISCONNECTED = 'disconnected',
// WAITING: means connected to the websocket but the counterparty (MetaMask or Dapps) isn't.
WAITING = 'waiting',
// TIMEOUT: means auto connect didn't establish link within given timeout
TIMEOUT = 'timeout',
// LINKED: is connected after handshake, using a different verb to avoid confusion to just being connected to the websocket and waiting for counterpart.
// LINKED is …
```

feat: expose channel id via hook + expose wallet status via sdk instance

---

packages/sdk/src/config.ts

Redirect to wallet on `personal_ecRecover`
(https://app.zenhub.com/workspaces/metamask-sdk-6359297a36f20292c13feca0/issues/gh/metamask/metamask-sdk/706)

feat: add support for personal_ecRecover

---

packages/sdk/src/services/Analytics.ts

Add missing sdkVersion in events sends from sdk package.

feat: add sdkVersion to analytics

---

package.json
packages/sdk-communication-layer/CHANGELOG.md
packages/sdk-communication-layer/package.json
packages/sdk-install-modal-web/CHANGELOG.md
packages/sdk-install-modal-web/package.json
packages/sdk-react-ui/CHANGELOG.md
packages/sdk-react-ui/package.json
packages/sdk-react/CHANGELOG.md
packages/sdk-react/package.json
packages/sdk/CHANGELOG.md
packages/sdk/package.json
packages/sdk/src/services/Analytics.ts

- feat: activate sourcemap support in all packages and resolve issues ([#730](https://github.com/MetaMask/metamask-sdk/pull/730))
- feat: add sdkVersion to analytics ([#726](https://github.com/MetaMask/metamask-sdk/pull/726))
- chore: reduce the bundle size ([#725](https://github.com/MetaMask/metamask-sdk/pull/725))
- feat: sdk bundle size opt methodology ([#722](https://github.com/MetaMask/metamask-sdk/pull/722))
- chore: use the 'debug' package as the new logger ([#716](https://github.com/MetaMask/metamask-sdk/pull/716))
- feat: add support for personal_ecRecover ([#707](https://github.com/MetaMask/metamask-sdk/pull/707))
- feat: expose channel id via hook + expose wallet status via sdk instance ([#704](https://github.com/MetaMask/metamask-sdk/pull/704))
- feat: automated github pages …

Release 49.0.0

---

packages/devnext/src/pages/demo.tsx
packages/devnext/src/styles/globals.css

This PR fixes mobile layout for devnext main demo using a media query that should cover most mobile devices. On mobile, the layout is reverted back to `flex-direction: row` which is the original layout prior to #719
https://github.com/MetaMask/metamask-sdk/assets/879484/96ea1351-804b-4084-b24d-eb5ab478cd98

fix: mobile layout for devnext main demo

---

.gitignore
packages/sdk-communication-layer/src/services/SocketService/MessageHandlers/handleSendMessage.ts
packages/sdk-react/src/MetaMaskProvider.tsx
packages/sdk/src/config.ts
packages/sdk/src/provider/initializeMobileProvider.ts
packages/sdk/src/provider/wrapExtensionProvider.ts

Limit the number of rpc calls that are tracked for analytics to the one redirecting to wallet on extension.
On mobile the list is:
```
'eth_sendTransaction',
'eth_signTypedData',
'eth_signTransaction',
'wallet_requestPermissions',
'wallet_switchEthereumChain',
'eth_signTypedData_v3',
'eth_signTypedData_v4',
'metamask_connectSign',
'metamask_connectWith',
'metamask_batch',
```

feat: restrict rpc method analytics

---

package.json
packages/sdk-communication-layer/CHANGELOG.md
packages/sdk-communication-layer/package.json
packages/sdk-install-modal-web/CHANGELOG.md
packages/sdk-install-modal-web/package.json
packages/sdk-react-ui/CHANGELOG.md
packages/sdk-react-ui/package.json
packages/sdk-react/CHANGELOG.md
packages/sdk-react/package.json
packages/sdk/CHANGELOG.md
packages/sdk/package.json

- feat: update the "@metamask/providers" package to version 15.0.0 ([#752](https://github.com/MetaMask/metamask-sdk/pull/752))
- feat: restrict rpc method analytics ([#755](https://github.com/MetaMask/metamask-sdk/pull/755))
- feat: rpc event tracking ([#745](https://github.com/MetaMask/metamask-sdk/pull/745))
- refactor(sdk): update blockedDomainCheck to remove regex ([#740](https://github.com/MetaMask/metamask-sdk/pull/740))
- chore: disable logs when running unit tests in CI ([#727](https://github.com/MetaMask/metamask-sdk/pull/727))
- feat: update the "@metamask/providers" package to version 15.0.0 ([#752](https://github.com/MetaMask/metamask-sdk/pull/752))
- feat: restrict rpc method analytics ([#755](https://github.com/MetaMask/metamask-sdk/pull/755))
- feat: rpc event tracking …

Release 51.0.0

---

packages/devreactnative/src/views/DappView.tsx
packages/sdk-react/package.json
packages/sdk-ui/package.json
packages/sdk/package.json
yarn.lock

adapt the "devreactnative" DApp for compatibility with new "metaMask/providers" version
https://github.com/MetaMask/metamask-sdk/assets/61094771/cef1f0e5-d274-4213-bc7d-04a2bd8698b4

fix: adapt the "devreactnative" DApp for compatibility with new "metaMask/providers" version

---

package.json
packages/sdk-react/CHANGELOG.md
packages/sdk-react/package.json
packages/sdk/CHANGELOG.md
packages/sdk/package.json

- fix: adapt the "devreactnative" DApp for compatibility with new "metaMask/providers" version ([#757](https://github.com/MetaMask/metamask-sdk/pull/757))
- fix: invalid provider state to undefined instead of null ([#758](https://github.com/MetaMask/metamask-sdk/pull/758))
- fix: adapt the "devreactnative" DApp for compatibility with new "metaMask/providers" version ([#757](https://github.com/MetaMask/metamask-sdk/pull/757))

Release 52.0.0

---

package.json
packages/sdk-react/CHANGELOG.md
packages/sdk-react/package.json
packages/sdk/CHANGELOG.md
packages/sdk/package.json

- feat: separately handle extension connectWith ([#767](https://github.com/MetaMask/metamask-sdk/pull/767))
- fix: normalize uppercase account addresses in SDKProvider, to resolve MaxListenersExceededWarning ([#766](https://github.com/MetaMask/metamask-sdk/pull/766))
- fix: normalize uppercase account addresses in SDKProvider, to resolve MaxListenersExceededWarning ([#766](https://github.com/MetaMask/metamask-sdk/pull/766))

Release 53.0.0

---

packages/devreact/.env.sample
packages/examples/create-react-app/.env.sample
packages/examples/nextjs-demo/.env.sample
packages/examples/react-with-custom-modal/.env.sample
packages/sdk-communication-layer/e2e/sdk-comm.test.ts
packages/sdk-communication-layer/src/config.ts

Change of production socket server URL from the previous `https://metamask-sdk-socket.metafi.codefi.network/` to the new `https://metamask-sdk.api.cx.metamask.io/`

feat: update prod socket server url

---

package.json
packages/sdk-communication-layer/CHANGELOG.md
packages/sdk-communication-layer/package.json
packages/sdk-react-ui/CHANGELOG.md
packages/sdk-react-ui/package.json
packages/sdk-react/CHANGELOG.md
packages/sdk-react/package.json
packages/sdk/CHANGELOG.md
packages/sdk/package.json

- feat: update prod socket server url ([#774](https://github.com/MetaMask/metamask-sdk/pull/774))
- feat: update prod socket server url ([#774](https://github.com/MetaMask/metamask-sdk/pull/774))
- feat: update the examples apps to the latest sdk version '0.17.2' ([#773](https://github.com/MetaMask/metamask-sdk/pull/773))
- feat: update the examples apps to the latest sdk version '0.17.2' ([#773](https://github.com/MetaMask/metamask-sdk/pull/773))

Release 54.0.0

---

packages/sdk-communication-layer/src/services/SocketService/EventListeners/handleMessage.ts
packages/sdk-communication-layer/src/services/SocketService/MessageHandlers/handleSendMessage.ts
packages/sdk-communication-layer/src/types/TrackingEvent.ts

Add `SDK_RPC_REQUEST_RECEIVED`  to acknowledge when wallet event has been received.

feat: add rpc received event

---

packages/sdk-communication-layer/src/services/SocketService/EventListeners/handleMessage.ts
packages/sdk-communication-layer/src/types/TrackingEvent.ts

- Add `sdk_rpc_request_done` to show when a method is received on the dapp side and differentiate with `sdk_rpc_request_received` to show when a method is received on the wallet side.
- remove outdated backward compatibility code

feat: sdk done event on dapp side

---

package.json
packages/sdk-communication-layer/CHANGELOG.md
packages/sdk-communication-layer/package.json
packages/sdk/CHANGELOG.md
packages/sdk/package.json

- fix: update the EIP_6369 provider info ([#788](https://github.com/MetaMask/metamask-sdk/pull/788))
- feat: sdk done event on dapp side ([#789](https://github.com/MetaMask/metamask-sdk/pull/789))

Release 56.0.0

---

package.json
packages/devnext/src/pages/_app.tsx
packages/sdk-ui/CHANGELOG.md
packages/sdk-ui/package.json
packages/sdk/CHANGELOG.md
packages/sdk/package.json
packages/sdk/src/services/MetaMaskSDK/ConnectionManager/connect.ts

- fix: issue preventing opting out of analytics ([#794](https://github.com/MetaMask/metamask-sdk/pull/794))
- feat: allow custom actions in MetaMask floating button ([#768](https://github.com/MetaMask/metamask-sdk/pull/768))
- fix: adapt the "devreactnative" DApp for compatibility with new "metaMask/providers" version ([#757](https://github.com/MetaMask/metamask-sdk/pull/757))

Release 57.0.0

---

packages/sdk/src/provider/SDKProvider.ts
packages/sdk/src/provider/initializeMobileProvider.ts
packages/sdk/src/sdk.ts
packages/sdk/src/services/MetaMaskSDK/ConnectionManager/connect.test.ts
packages/sdk/src/services/MetaMaskSDK/ConnectionManager/connect.ts
packages/sdk/src/services/MetaMaskSDK/InitializerManager/performSDKInitialization.ts

This PR fixes the logger initialization which was always enabled by default.
It also removed the need to default to ethereum when chain is unknown since we know store the last chain locally.

feat: logging initialization

---

packages/devnext/src/pages/_app.tsx
packages/sdk-communication-layer/src/services/RemoteCommunication/ConnectionManager/initCommunicationLayer.ts
packages/sdk-communication-layer/src/types/OriginatorInfo.ts
packages/sdk-install-modal-web/src/InstallModal.tsx
packages/sdk-install-modal-web/src/ModalLoader.tsx
packages/sdk/src/Platform/MetaMaskInstaller.test.ts
packages/sdk/src/Platform/MetaMaskInstaller.ts
packages/sdk/src/sdk.ts
packages/sdk/src/services/Analytics.test.ts
packages/sdk/src/services/MetaMaskInstaller/redirectToProperInstall.test.ts
packages/sdk/src/services/MetaMaskInstaller/redirectToProperInstall.ts
packages/sdk/src/services/MetaMaskSDK/InitializerManager/setupAnalytics.test.ts
packages/sdk/src/services/MetaMaskSDK/InitializerManager/setupAnalytics.ts
packages/sdk/src/services/MetaMaskSDK/InitializerManager/setupRemoteConnectionAndInstaller.test.ts
packages/sdk/src/services/MetaMaskSDK/InitializerManager/setupRemoteConnectionAndInstaller.ts
packages/sdk/src/services/RemoteConnection/ModalManager/showInstallModal.ts
packages/sdk/src/services/RemoteConnection/RemoteConnection.ts
packages/sdk/src/ui/InstallModal/InstallModal-web.ts

- Fix desktop onboarding.
- Let user set `preferDesktop` to display the 'Desktop' tab by default.

fix: preferDesktop and onboarding

---

packages/sdk-socket-server-next/package.json

This PR bumps the socket-server-next version to 2.0.1 for us to get a proper version in the /version endpoint.

chore: Bump the socket-server-next version to 2.0.1 for the /version endpoint

---

packages/sdk/src/services/RemoteConnection/ConnectionManager/startConnection.ts

In order to integrate with wallet connectors, developer may want to access the qrcode url without actually initiating the deeplink.
The problem is we cannot know the url ahead of time and there is no direct dependencies between sdk and the connection provider.
A workaround is to directly emit display_uri on the provider in order to inform potential wallet connector of the actual uri.

feat: emit url event

---

packages/sdk-communication-layer/src/services/SocketService/ChannelManager/createChannel.ts
packages/sdk/src/config.ts
packages/sdk/src/sdk.test.ts
packages/sdk/src/sdk.ts
packages/sdk/src/services/MetaMaskSDK/ConnectionManager/terminate.test.ts
packages/sdk/src/services/MetaMaskSDK/ConnectionManager/terminate.ts
packages/sdk/src/services/RemoteConnection/ModalManager/showInstallModal.test.ts
packages/sdk/src/services/RemoteConnection/ModalManager/showInstallModal.ts

Remove console log leakage and implement `wallet_revokePermissions` on terminate.
https://github.com/MetaMask/metamask-sdk/issues/906

feat: wallet_revokePermissions on terminate

---

package.json
packages/sdk-communication-layer/CHANGELOG.md
packages/sdk-communication-layer/package.json
packages/sdk-react-ui/CHANGELOG.md
packages/sdk-react-ui/package.json
packages/sdk-react/CHANGELOG.md
packages/sdk-react/package.json
packages/sdk/CHANGELOG.md
packages/sdk/package.json

- chore: terminate on 'ACCOUNTS_CHANGED' event when accounts are zero ([#909](https://github.com/MetaMask/metamask-sdk/pull/909))
- chore: terminate on 'ACCOUNTS_CHANGED' event when accounts are zero ([#909](https://github.com/MetaMask/metamask-sdk/pull/909))
- chore: terminate on 'ACCOUNTS_CHANGED' event when accounts are zero ([#909](https://github.com/MetaMask/metamask-sdk/pull/909))
- feat: cleanup leaking console logs ([#907](https://github.com/MetaMask/metamask-sdk/pull/907))

Release 72.0.0

---

packages/sdk/src/provider/extensionProviderHelpers/handleBatchMethod.test.ts
packages/sdk/src/provider/extensionProviderHelpers/handleBatchMethod.ts
packages/sdk/src/provider/extensionProviderHelpers/handleConnectSignMethod.test.ts
packages/sdk/src/provider/extensionProviderHelpers/handleConnectSignMethod.ts
packages/sdk/src/provider/extensionProviderHelpers/handleConnectWithMethod.test.ts
packages/sdk/src/provider/extensionProviderHelpers/handleConnectWithMethod.ts
packages/sdk/src/provider/wrapExtensionProvider.test.ts
packages/sdk/src/provider/wrapExtensionProvider.ts

Fixed the `connectAndSign` method error when using MetaMask SDK. Updated `wrapExtensionProvider` to handle `metamask_connectSign` method correctly, ensuring smooth connection and flow.
What We Did:
- Updated `wrapExtensionProvider` to handle `metamask_connectSign` method.
- Enhanced logic for `request` method wrapper to make sure other special methods work well with the extension.
https://github.com/MetaMask/metamask-sdk/assets/61094771/9e2044a4-5d28-4d59-816a-5aaf7fdbed44
* Fixes [#12345](https://github.com/MetaMask/metamask-sdk/issues/793)

fix: update the 'request' method wrapper logic in 'wrapExtensionProvider' to handle connectAndSign issues

---

packages/sdk/src/sdk.ts

This PR removes the `defaultReadOnlyChainId` option from the SDK options configuration. 
This option is not utilized anywhere in the codebase, so its presence is unnecessary.

chore: removes the 'defaultReadOnlyChainId' option from the SDK options

---

package.json
packages/sdk-communication-layer/CHANGELOG.md
packages/sdk-communication-layer/package.json
packages/sdk-install-modal-web/CHANGELOG.md
packages/sdk-install-modal-web/package.json
packages/sdk-react-ui/CHANGELOG.md
packages/sdk-react-ui/package.json
packages/sdk-react/CHANGELOG.md
packages/sdk-react/package.json
packages/sdk/CHANGELOG.md
packages/sdk/package.json

- chore: removes the 'defaultReadOnlyChainId' option from the SDK options ([#919](https://github.com/MetaMask/metamask-sdk/pull/919))
- chore: update SDK dependencies to resolve version conflicts ([#921](https://github.com/MetaMask/metamask-sdk/pull/921))
- chore: update the 'request' method in the 'wrapExtensionProvider' to throw an error when RPC calls fail ([#917](https://github.com/MetaMask/metamask-sdk/pull/917))
- chore: removes the 'defaultReadOnlyChainId' option from the SDK options ([#919](https://github.com/MetaMask/metamask-sdk/pull/919))
- chore: update SDK dependencies to resolve version conflicts ([#921](https://github.com/MetaMask/metamask-sdk/pull/921))
- chore: update the 'request' method in the 'wrapExtensionProvider' to throw an error when RPC calls fail …

Release 74.0.0

---

packages/examples/react-metamask-button/README.md
packages/examples/react-metamask-button/src/App.js

Adds a warning to the react-metamask-button example dapp since a recent [bug found](https://github.com/MetaMask/metamask-sdk/issues/923) in it is causing the mobile wallet to crash.
This message should be removed once the issue is fixed.

chore: add warning message to react-metamask-button example dapp

---

packages/sdk-install-modal-web/package.json
yarn.lock

This update addresses the peer dependency warning by updating the `peerDependencies` of the `@metamask/sdk-install-modal-web` package. 
The warning indicated an unmet peer dependency for i18next. 
The following changes have been made:
•	Updated `i18next` peer dependency to version `23.11.5` to match the version found in `@metamask/sdk`
That's the warning:

 chore: update peerDependencies of ‘@metamask/sdk-install-modal-web’ to resolve installation warnings

---

package.json
packages/sdk-install-modal-web/CHANGELOG.md
packages/sdk-install-modal-web/package.json
packages/sdk-react-native/CHANGELOG.md
packages/sdk-react-native/package.json
packages/sdk-react-ui/CHANGELOG.md
packages/sdk-react-ui/package.json
packages/sdk-react/CHANGELOG.md
packages/sdk-react/package.json
packages/sdk/CHANGELOG.md
packages/sdk/package.json

- chore: update the '@metamask/providers' package to version '16.1.0'
- chore: update the '@metamask/providers' package to version '16.1.0'
- chore: update the 'babel' packages ([#939](https://github.com/MetaMask/metamask-sdk/pull/939))
- chore: update the '@metamask/providers' package to version '16.1.0'
- chore: update the 'babel' packages ([#939](https://github.com/MetaMask/metamask-sdk/pull/939))
- chore: update the 'reactNativeSdkDemo' example to 'sdk-react-native' version 0.3.1 ([#936](https://github.com/MetaMask/metamask-sdk/pull/936))
- chore: update the 'sdk-react-native' package native modules versions ([#935](https://github.com/MetaMask/metamask-sdk/pull/935))
- feat: add script to align version before publishing ([#902](https://github.com/MetaMask/metamask-sdk/pull/902))
- …

Release 75.0.0

---

package.json
packages/sdk-react-native/CHANGELOG.md
packages/sdk-react-native/package.json

- chore: update the 'metamask-ios-sdk' version to '0.7.3' in the 'sdk-react-native' package ([#944](https://github.com/MetaMask/metamask-sdk/pull/944))

Release 77.0.0

---

packages/sdk-react-native/src/NativePackageMethods.ts

ensure URL event listener is only added on iOS in the `sdk-react-native` package

chore: (sdk-react-native) ensure URL event listener is only added on iOS 

---

packages/sdk/src/services/MetaMaskSDK/InitializerManager/initializeProviderAndEventListeners.ts
packages/sdk/src/services/MetaMaskSDK/InitializerManager/performSDKInitialization.test.ts
packages/sdk/src/services/MetaMaskSDK/InitializerManager/performSDKInitialization.ts

Fixes the extensionOnly default to true to SDK initialization.

fix: adds extensionOnly default to true to SDK initialization

---

package.json
packages/sdk-communication-layer/CHANGELOG.md
packages/sdk-communication-layer/package.json
packages/sdk-react-ui/CHANGELOG.md
packages/sdk-react-ui/package.json
packages/sdk-react/CHANGELOG.md
packages/sdk-react/package.json
packages/sdk/CHANGELOG.md
packages/sdk/package.json

- feat: adds `connector` analytical property ([#947](https://github.com/MetaMask/metamask-sdk/pull/947))
- fix: adds extensionOnly default to true to SDK initialization ([#962](https://github.com/MetaMask/metamask-sdk/pull/962))
- feat: sets extensionOnly default to true ([#956](https://github.com/MetaMask/metamask-sdk/pull/956))
- chore: bump .change files ([#957](https://github.com/MetaMask/metamask-sdk/pull/957))
- feat: improve open deeplink on IOS Chrome ([#948](https://github.com/MetaMask/metamask-sdk/pull/948))
- fix: adds extensionOnly default to true to SDK initialization ([#962](https://github.com/MetaMask/metamask-sdk/pull/962))
- feat: sets extensionOnly default to true ([#956](https://github.com/MetaMask/metamask-sdk/pull/956))
- chore: bump .change files …

Release 78.0.0

---

package.json
packages/sdk-react-native/CHANGELOG.md
packages/sdk-react-native/package.json

- feat: update iOS and Android SDKs to latest versions in 'sdk-react-native' ([#966](https://github.com/MetaMask/metamask-sdk/pull/966))
- chore: ensure 'setupDeeplinkHandling' is running only on iOS ([#953](https://github.com/MetaMask/metamask-sdk/pull/953))
- chore: (sdk-react-native) ensure URL event listener is only added on iOS  ([#952](https://github.com/MetaMask/metamask-sdk/pull/952))

Release 79.0.0

---

packages/sdk-communication-layer/src/services/RemoteCommunication/ConnectionManager/initCommunicationLayer.ts
packages/sdk-socket-server-next/src/api-config.ts
packages/sdk/src/services/MetaMaskSDK/InitializerManager/setupAnalytics.test.ts
packages/sdk/src/services/MetaMaskSDK/InitializerManager/setupAnalytics.ts

Change the default value for `dappId` to `N/A` instead of an empty string

feat: change the default value for 'dappId' to 'N/A' instead of an empty string

---

packages/sdk-react-native/src/NativePackageMethods.ts

This PR filters the urls that are handled by the sdk to only those with host `mmsdk`. All deeplink communication from the wallet to the dapp is done via deeplinks with this host. Currently, the sdk attempts to handle all deeplinks with the dapp scheme, including those not from metamask. Deeplink format: `${dappScheme}://mmsdk?message=${base64Message}`

chore: filter metamask urls

---

packages/sdk-communication-layer/src/services/SocketService/ConnectionManager/handleJoinChannelResult.ts
packages/sdk-communication-layer/src/services/SocketService/ConnectionManager/resume.test.ts
packages/sdk-communication-layer/src/services/SocketService/ConnectionManager/resume.ts
packages/sdk/src/provider/initializeMobileProvider.ts

- Fixes on resume for wallet in order to use the new join channel flow

feat: experimental deeplink protocoll

---

packages/sdk-communication-layer/src/services/RemoteCommunication/MessageHandlers/handleWalletInitMessage.ts
packages/sdk-communication-layer/src/services/SocketService/ConnectionManager/resume.test.ts
packages/sdk-communication-layer/src/services/SocketService/ConnectionManager/resume.ts
packages/sdk-communication-layer/src/services/SocketService/MessageHandlers/handleSendMessage.ts
packages/sdk-socket-server-next/src/protocol/handleMessage.ts
packages/sdk/src/services/RemoteCommunicationPostMessageStream/onMessage.ts
packages/sdk/src/services/RemoteCommunicationPostMessageStream/write.test.ts
packages/sdk/src/services/RemoteCommunicationPostMessageStream/write.ts

- fully working deeplink protocol
- compatible with wagmi

feat: full deeplink protocol

---

packages/examples/reactNativeSdkDemo/ios/Podfile.lock
packages/examples/reactNativeSdkDemo/package.json
packages/examples/reactNativeSdkDemo/yarn.lock

Update the `reactNativeSdkDemo` example dapp to the latest sdk versions

chore: update react native example dapp to latest sdk version

---

package.json
packages/sdk-react-native/CHANGELOG.md
packages/sdk-react-native/package.json

- chore: improve the deeplink handling for MetaMask SDK on iOS ([#1002](https://github.com/MetaMask/metamask-sdk/pull/1002))

Release 84.0.0

---

packages/examples/reactNativeSdkDemo/src/views/DappView.tsx
packages/sdk-react-native/android/build.gradle
packages/sdk-react-native/ios/MetaMaskReactNativeSdk.swift
packages/sdk-react-native/metamask-sdk-react-native.podspec
packages/sdk-react-native/src/NativePackageMethods.ts

This PR updates the connect method to return an array of accounts instead of the selected account to match it with other sdks. The PR also updates dapp demo to likewise

chore: update connect method to return accounts array

---

package.json
packages/sdk-react-native/CHANGELOG.md
packages/sdk-react-native/package.json

- chore: add handling of infura api ([#1025](https://github.com/MetaMask/metamask-sdk/pull/1025))
- chore: update connect method to return accounts array ([#1023](https://github.com/MetaMask/metamask-sdk/pull/1023))
- chore: display the right 'rn-sdk' version in the wallet side ([#1015](https://github.com/MetaMask/metamask-sdk/pull/1015))

Release 88.0.0

---

package.json
packages/sdk-react-ui/CHANGELOG.md
packages/sdk-react-ui/package.json
packages/sdk-react/CHANGELOG.md
packages/sdk-react/package.json
packages/sdk/CHANGELOG.md
packages/sdk/package.json

- fix: update the `initializeMobileProvider` function to ensure it returns all connected accounts on mobile ([#1031](https://github.com/MetaMask/metamask-sdk/pull/1031))
- fix: update the `initializeMobileProvider` function to ensure it returns all connected accounts on mobile ([#1031](https://github.com/MetaMask/metamask-sdk/pull/1031))
- fix: update the `initializeMobileProvider` function to ensure it returns all connected accounts on mobile ([#1031](https://github.com/MetaMask/metamask-sdk/pull/1031))

Release 91.0.0

---

packages/sdk-react-native/metamask-sdk-react-native.podspec

chore: bump ios sdk version

---

packages/sdk-socket-server-next/src/analytics-api.ts
packages/sdk-socket-server-next/src/logger.ts

- enable json logger
- prevent sending error to dapp (keep similar behavior has previous versions)

feat: server log and error handling

---

packages/sdk-communication-layer/src/services/SocketService/ConnectionManager/ping.test.ts
packages/sdk-communication-layer/src/services/SocketService/ConnectionManager/ping.ts

Change the ping method on communication layer to query server for pending messages.

feat: ping to retrieve pending messages from server

---

packages/sdk-communication-layer/src/Analytics.ts
packages/sdk/src/sdk.test.ts
packages/sdk/src/sdk.ts
packages/sdk/src/services/Analytics.ts

- Automatically set the dappMetadata on web. Previous behavior was to use the title if url not set.
- Align event format to spread originatorInfo data in the event

feat: default web url metadata

---

packages/sdk-socket-server-next/src/analytics-api.ts
packages/sdk/src/provider/initializeMobileProvider.ts

Since Async Key exchange, the mobile directly returns the account and chainId before the "with" method is processed which can potentially trigger an eth_getBalance on sdk_react. The sdk historically was waiting for the first rpc response to treat as response to connectWith which is why it could treat response to getBalance instead of the "with" method.
This PR fixes this issue.
Fixes: https://consensyssoftware.atlassian.net/jira/software/projects/SDK/boards/711?selectedIssue=SDK-61&sprintStarted=true

fix: connectWith potnetially returning incorrect response

---

packages/sdk-socket-server-next/src/analytics-api.ts

- always generate dappId events when missing

feat: generate new dappId when missing

---

packages/sdk-socket-server-next/package.json

chore: dummy bumps socket server version to fix deploys

---

packages/devnext/src/pages/demo.tsx
packages/sdk/src/provider/extensionProviderHelpers/handleBatchMethod.test.ts
packages/sdk/src/provider/extensionProviderHelpers/handleBatchMethod.ts
packages/sdk/src/provider/wrapExtensionProvider.test.ts
packages/sdk/src/provider/wrapExtensionProvider.ts

This PR fixes a bug where the extension provider invokes the `metamask_batch` request logic correctly, but then also sends a `metamask_batch` request again. This (at best) causes the requests to be sent individually, then all at once or (at worst) causing `metamask_batch` to break entirely if the extension doesn't support the RPC
Currently, the latter case happens. The requests are sent individually, but then errors because it then tries to send `metamask_batch` and the extension doesn't support that
With the fixed logic in `handleBatchMethod`, the extension **and SDK** return the correct result
This PR also updates the unit tests for `handleBatchMethod` to be more robust to ensure this behavior doesn't regress.
This likely closes #1045 
- [N/A] I've updated documentation (JSDoc, …

fix: improper implementation of handleBatchMethod + more robust tests

---

packages/devnext/src/pages/_app.tsx
packages/sdk/src/provider/initializeMobileProvider.ts

Some clients implementation rely on the `display_uri` event being re-triggered every time the modal is opened.
This PR automatically republish the uri so that clients don't have to implement their own cache of the display_uri.

feat: always re-emit display uri event

---

packages/devnext/src/pages/_app.tsx
packages/devnext/src/pages/demo.tsx
packages/sdk/src/config.ts
packages/sdk/src/provider/extensionProviderHelpers/handleConnectWithMethod.ts
packages/sdk/src/provider/initializeMobileProvider.ts

Emit a new event to inform clients using provider such as wagmi of the response from `connectWith` or `connectAndSign`.
This allows for better flexibility for the developer if the connector integration only returns the list of account.

feat: emit connectWithResponse event

---

packages/sdk/src/provider/initializeMobileProvider.ts

The `display_uri ` should be just a string containing the uri, not an object.
See first event sent here: https://github.com/MetaMask/metamask-sdk/blob/986648007c09eef112708d5d08a0e47eac3cd7d3/packages/sdk/src/services/RemoteConnection/ConnectionManager/startConnection.ts#L178

fix: display_uri event malformed

---

packages/sdk-communication-layer/src/RemoteCommunication.ts
packages/sdk-communication-layer/src/services/RemoteCommunication/MessageHandlers/handleWalletInitMessage.ts
packages/sdk/src/services/RemoteConnection/RemoteConnection.ts

There is a race condition happening when the sdk is using the rpc protocol and restore its connection.
Because the socket layer receives the connection event before the channel config is restored from the storage, we loose the previous storage containing wallet version and rpcprotocol availability.
- Fixes https://consensyssoftware.atlassian.net/jira/software/projects/SDK/boards/711?selectedIssue=SDK-99&sprintStarted=true

fix: rpc protocol resetting after refresh

---

packages/sdk/src/utils/get-browser-extension.test.ts
packages/sdk/src/utils/get-browser-extension.ts

I’ve discovered an issue with the SDK (pure JavaScript and wagmi).
The SDK tests the boolean `window.ethereum.isMetaMask` to detect if the extension is installed.
However, some other extensions use the same boolean to imitate MetaMask (e.g., Uniswap, Zerion, Rabby, etc.), and it works…
So, if the MetaMask extension is not installed, but one of those wallets is, the SDK will open the “fake” extension instead of the connection modal.
Wagmi has a similar detection on their side, but they don’t take into account the “Uniswap Wallet.”
I also created a PR on Wagmi to add Uniswap to their detection test.
Here’s a demo video.
https://github.com/user-attachments/assets/be461d80-436b-475c-9fd5-9c692b9010bd

feat: fake metamask wallet detection

---

packages/sdk/src/services/MetaMaskSDK/ConnectionManager/connectAndSign.ts
packages/sdk/src/utils/hex.utils.test.ts
packages/sdk/src/utils/hex.utils.ts

Always convert non hex string to hex when using connectAndSign.

fix: connectAndSign send as hexString

---

.github/workflows/gh-pages.yml

This pull request updates the token that is used for gh-pages deployments to a MetaMaskBot token as seen on other repositories. I've also adjusted the job to run upon merge to the main branch rather than on pull requests as well. If this behaviour was intentional, please let me know and we can explore how to support this updated token on branches as well.
Once this pull request is merged, please to a test deployment to ensure that the deployment functions as expected.

Update token used for gh-pages deployments

---

.github/workflows/gh-pages.yml

This pull request updates the deploy workflow to explicitly note the environment its part of (github-pages) and use the `personal_token` field as per the `peaceiris/actions-gh-pages` docs.
This mimics a similar setup as the Website repository here: https://github.com/MetaMask/website/blob/master/.github/workflows/integrate.yml

Fix deploy workflow

---

packages/sdk/src/sdk.ts

We now recommend using `display_uri` event for implementing custom display related action.

feat: deprecate getUniversalLink in favor or display_uri

---

packages/sdk-socket-server-next/package.json
packages/sdk-socket-server-next/src/index.ts
packages/sdk-socket-server-next/src/metrics.ts
packages/sdk-socket-server-next/src/socket-config.ts
yarn.lock

The current state uses a custom metrics extraction function that manually calculates and formats metrics for total connected clients and total rooms. This approach is limited in scope and requires manual maintenance to add or modify metrics.
The solution introduces the use of the Prometheus client library ('prom-client') to handle metrics collection and formatting. This change offers several advantages:
1. Standardized metrics format compatible with Prometheus
2. Automatic collection of numerous Node.js and process-level metrics out-of-the-box
3. Easy addition and customization of application-specific metrics
The changes include:
- Adding 'prom-client' as a dependency
- Replacing the custom 'extractMetrics' function with Prometheus Registry and Gauge metrics
- Updating the metrics …

chore: add prom client

---

scripts/build-static-dapps.sh

Patches an issue where for new branch deployments the folder would not be added to the index.html of the deployments root

fix: fixes an issue when the folder needed to be created

---

packages/sdk/src/services/MetaMaskSDK/InitializerManager/setupInfuraProvider.ts

This fixes issues with using read-only RPCs with Infura on Sepolia. This was caused by the wrong chainId being mapped to Sepolia in the Infura RPC URL map
N/A
- [N/A] I've updated the test suite for new or updated code as appropriate
- [N/A] I've updated documentation (JSDoc, Markdown, etc.) for new or updated code as appropriate
- [N/A] I've highlighted breaking changes using the "BREAKING" category above as appropriate

fix: chainId for sepolia in infura rpc map

---

packages/sdk-socket-server-next/src/analytics-api.ts
packages/sdk-socket-server-next/src/metrics.ts
packages/sdk-socket-server-next/src/middleware-metrics.ts

The current analytics endpoint ('/evt') lacks comprehensive monitoring and observability features, making it difficult to:
- Track request performance and error rates
- Monitor Redis cache effectiveness
- Understand SDK usage patterns and event distributions
- Debug issues in production
This PR adds metrics to addresses these gaps by:
1. Implementing a new metrics middleware that tracks request duration and status codes
2. Adding detailed counters for analytics events with dimensions for platform, SDK version, and event types
3. Tracking Redis cache hit/miss rates
4. Adding error tracking with error type categorization

chore: add metrics to analytics

---

.husky/prepare-commit-msg

Because the monorepo uses husky, it prevents calling the user installed global git hooks.
This allow user to still run their custom git hooks.

feat(root): expose global github hooks while using husky

---

packages/sdk/src/services/RemoteConnection/EventListeners/setupListeners.ts

chore: remove the alert of 'SDK Connection has been terminated'

---

package.json
packages/sdk-communication-layer/package.json
packages/sdk/package.json
yarn.lock

Updates `secp256k1` to version 5.0.1 and related ECIES dependencies to prevent a vulnerability where private keys could be extracted through malicious ECDH operations using invalid curve points.
- Pin `secp256k1` to `^5.0.1` in resolutions
- Update `eciesjs` dependencies across SDK packages
- Adjust peer dependency requirements for `eciesjs`
Prevents an attack vector where an attacker could extract private keys using specially crafted public keys with low-cardinality curves through as few as 11 ECDH sessions.
- https://github.com/advisories/GHSA-584q-6j8j-r5pm
- https://consensyssoftware.atlassian.net/jira/software/projects/SDK/boards/711?selectedIssue=SDK-131&sprintStarted=true

fix: potential security issue with secp256k1

---

packages/sdk/src/services/Ethereum.ts
packages/sdk/src/utils/get-browser-extension.test.ts
packages/sdk/src/utils/get-browser-extension.ts

This PR modernizes our wallet provider detection by prioritizing the EIP-6963 standard while maintaining backwards compatibility. It simplifies our codebase by removing complex wallet-specific detection logic and improves reliability across different browser environments, particularly on iOS.
- ✨ Prioritize EIP-6963 for wallet provider detection
- 🔥 Remove legacy wallet detection heuristics (flags like `isMetaMask`, `isBraveWallet`, etc.)
- 🛠️ Simplify fallback logic to use `window.ethereum` only when necessary
- 🐛 Add error handling for Brave iOS where `window` properties are read-only
- 📝 Improve test coverage and reduce test complexity
- Restructured provider detection flow:
1. Attempt EIP-6963 provider detection first
2. Fallback to `window.ethereum` only for non-MetaMask scenarios
3. …

refactor(sdk): modernize wallet provider detection with EIP-6963

---

.github/workflows/deploy-cdn.yml
.github/workflows/deploy-static.yml
scripts/deploy-cdn.sh
scripts/deploy-static.sh

This PR aims to add a dedicated workflow to deploy to GH pages a build minified version of the SDK to be used in `pure-javascript` deploy types.

feat: adds CDN deployments to gh pages

---

packages/sdk/src/services/MetaMaskSDK/InitializerManager/setupExtensionPreferences.ts

Historically, when creating the initial versions of the SDK we wanted to create a mechanism to detect when a connection was terminated while the dapp was not on focus both on mobile and extension.
On mobile to mobile and mobile - desktop interactions we're able to do this async via socket server but with extension since we're wrapping the already existent injected provider, we don't make use of socket.io code so for the initial versions of the MMSDK we assumed that getting an event `accountsChanged=[]` would mean that the permitted accounts were removed from extension and thus the connection is no longer valid. 
The problem with this approach is that when MetaMask extension is simply locked while keeping permissions it sends an `accountsChanged=[]` event as required by EIP-1193.
This PR …

chore: removes sdk terminate when accountsChanged comes in empty

---

packages/sdk-install-modal-web/stencil.config.ts
packages/sdk-react/package.json
packages/sdk-react/rollup.config.js
packages/sdk/package.json
packages/sdk/rollup.config.js
yarn.lock

This PR fixes a few things when bundling the SDK with projects using WebPack
1. Disable `es5Builds` in StencilJS
- This is not needed and is causing issues with not including webpack/vite magic comments in import statements 
2. Add a `/* webpackIgnore: true */` comment to the generated dynamic import that StencilJS creates
- This is done via a custom rollup plugin to inject the comment via a regex match
3. Replace the `globals()` plugin with a more modern polyfill
- Since StencilJS is no longer building es5, the old `globals()` plugin was having parsing issues. This plugin has been replaced with the [modern replacement](https://www.npmjs.com/package/rollup-plugin-polyfill-node)
- The configuration for this plugin needs `include: null` to ensure that all files (including source files) are …

fix: Tell webpack about dynamic import + fixed polyfills

---

packages/sdk-install-modal-web/src/components.d.ts
packages/sdk-install-modal-web/src/components/mm-install-modal/mm-install-modal.tsx
packages/sdk-install-modal-web/src/components/mm-select-modal/mm-select-modal.tsx
packages/sdk/src/ui/InstallModal/InstallModal-web.ts
packages/sdk/src/ui/InstallModal/Modal-web.ts

This PR fixes a bug that was introduced when migrating to the new web component based modals. The initial tab displayed was always mobile, even if `preferDesktop` was set to `true`.
N/A
- [N/A] I've highlighted breaking changes using the "BREAKING" category above as appropriate

Set initial modal tab based on preferDesktop option

---

packages/sdk/package.json

This PR removes the exports field from the Metamask SDK package.json to resolve build issues experienced in Next.js + Wagmi integrations. It also upgrades TypeScript to ensure compatibility and maintain stable compilation after removing the exports configuration.
Re-create https://github.com/MetaMask/metamask-sdk/pull/1161

fix: re-create nextjs build fix pr

---

packages/sdk-socket-server-next/src/analytics-api.ts
packages/sdk/src/services/RemoteCommunicationPostMessageStream/write.ts

This PR addresses two critical analytics-related issues that were causing missing dapp details and incomplete event tracking:
When using the deeplink protocol, the SDK would directly open the deeplink without going through the network path, causing analytics events to be missed. This PR ensures analytics events are properly tracked regardless of the communication method used.
- Added analytics tracking for SDK RPC requests when not using network communication
- Implemented `SendAnalytics` function to log `SDK_RPC_REQUEST` events with method and source information
- Maintained existing network path analytics while adding coverage for direct deeplink interactions
The system was not properly validating cached dapp information in Redis, leading to events being sent without proper dapp …

fix(analytics): improve dapp details tracking and SDK RPC request analytics

---

packages/sdk/src/services/RemoteCommunicationPostMessageStream/write.ts

This PR simplifies the RPC message handling strategy by sending requests through both network and deeplink channels simultaneously, allowing the wallet to process whichever arrives first. This approach eliminates edge cases and improves reliability while maintaining backward compatibility.
- Previously, we conditionally sent RPC requests either via network or deeplink based on protocol availability
- Now, we:
1. Always send RPC requests via network for consistency and reliability
2. Allow deeplink protocol to handle requests in parallel when available
3. Let the wallet deduplicate and process only the first received request
4. Remove conditional analytics sending since it's now handled uniformly
No migration steps required. This is a transparent change that maintains backward …

refactor(sdk): always send RPC requests via network and deeplink

---

packages/sdk/src/services/MetaMaskInstaller/startDesktopOnboarding.ts

The change replaces delete window.ethereum with window.ethereum = undefined to safely clear the ethereum property without removing it from the window object. This approach ensures safer handling of the ethereum provider and avoids side effects from property deletion.
Fixes #1131

fix(MetaMaskInstaller): replace delete with assignment to undefined for window.ethereum

---

packages/sdk/src/services/MetaMaskSDK/InitializerManager/setupExtensionPreferences.test.ts
packages/sdk/src/services/MetaMaskSDK/InitializerManager/setupExtensionPreferences.ts

Historically, we used to call sdk.terminate() when receiving an accountsChanged=[] event thinking that permissions had been revoked from the extension. 
The problem with this is that EIP-1193 requires the extension to send accountsChanged=[] when locking the extension (to be changed) meaning that the accounts are no longer available and that it needs to e unlocked for them to be available again. 
It is scheduled for extension to stop emitting this event but because we need to keep backward compatibility until most users have the new extension version, we need to implement a workaround for this specific case. Upon discussing with wallet-api members it was decided that SDK would call getPermissions when receiving accountsChanged=[] since this call returns permissions even when the wallet is …

chore: call getPermissions on accountsChanged when using extension

---

packages/sdk-install-modal-web/src/components/mm-install-modal/mm-install-modal.tsx
packages/sdk-install-modal-web/src/components/mm-select-modal/mm-select-modal.tsx

This PR fixes a scope-related bug in the modal components where event handlers were losing their `this` context. The issue affected click handlers in both the install and select modal components, potentially causing undefined errors when attempting to invoke methods.
These changes fix potential runtime errors that could occur when users interact with modal buttons and overlays. No breaking changes or migration steps are required as this is a bug fix that maintains the existing API.

fix: correct event handler binding in modal components

---

packages/sdk/src/constants.ts
packages/sdk/src/utils/eip6963RequestProvider.test.ts
packages/sdk/src/utils/eip6963RequestProvider.ts

This PR extends our EIP-6963 provider detection to support MetaMask Flask alongside the main MetaMask provider.
- Added support for MetaMask Flask RDNS identifier (`io.metamask.flask`)
- Updated provider validation logic to check against multiple RDNS values
- Added test coverage for Flask provider detection
- Modified `METAMASK_EIP_6369_PROVIDER_INFO.RDNS` to be an array that includes both `io.metamask` and `io.metamask.flask`
- Updated the provider validation logic in `eip6963RequestProvider.ts` to use `includes()` for RDNS checking
- Added a new test case specifically for MetaMask Flask provider detection
This change is backwards compatible and doesn't require any migration steps. It simply adds support for detecting MetaMask Flask providers while maintaining existing functionality for …

feat: add MetaMask Flask provider support for EIP-6963

---

packages/sdk-react/src/EventsHandlers/useHandleTerminateEvent.test.tsx
packages/sdk-react/src/EventsHandlers/useHandleTerminateEvent.ts
packages/sdk-react/src/MetaMaskProvider.spec.tsx
packages/sdk-react/src/MetaMaskProvider.tsx
packages/sdk/src/services/MetaMaskSDK/ConnectionManager/terminate.test.ts
packages/sdk/src/services/MetaMaskSDK/ConnectionManager/terminate.ts

This PR aims to improve the react connected hook when using the extension. Previously, the connected hook would always be true when using extension because `window.ethereum.isConnected` is always true as long as the extension is being detected. This now verifies if we have an account present meaning that it is actually connected to extension. If no account is present then it assumes it has been disconnected like mobile does (even though mobile relies on socket events to do this).
- terminate.ts. now emits a terminate event when extensionOnly is true (the current default)
- adds a new useHandleTerminateEvent.ts hook to handle the behavior of some connected hooks such as `connecting` and `connected`
- MetaMaskProvider.tsx now sets `connected` based on the existence of an account or not …

feat: improves the react connected hook when using extension & emit terminate when using extension

---

packages/sdk-install-modal-web/src/components.d.ts
packages/sdk-install-modal-web/src/components/mm-install-modal/mm-install-modal.tsx
packages/sdk/src/ui/InstallModal/Modal-web.ts

This PR fixes the issue for: https://github.com/wevm/wagmi/issues/4504

fix: user rejection bug

---

packages/sdk/package.json
packages/sdk/rollup.config.js
yarn.lock

This PR rolls back the recent upgrade of `@metamask/providers` from v18.3.1 to v16.1.0 due to compatibility issues discovered with Next.js applications. This is a temporary measure until we can properly address the integration challenges as part of the upcoming multichain API deployment.
- Reverted `@metamask/providers` dependency from `^18.3.1` to `16.1.0` in `packages/sdk/package.json`
- Removed `@metamask/providers` from rollup external dependencies list
- Cleaned up related circular dependency warnings in rollup configuration
This rollback:
- Resolves immediate compatibility issues with Next.js applications
- Returns the SDK to a known stable state
- Postpones the providers upgrade to align with future multichain API deployment
1. Dependency management:
- Pinned `@metamask/providers` …

feat(sdk): rollback @metamask/providers to 16.1.0 due to Next.js compatibility issues

---

.github/workflows/lint-build-test.yml
.github/workflows/publish-release.yml

This PR updates our GitHub Actions workflows to use artifacts instead of caching for better control over build outputs. The changes affect the `lint-build-test.yml` and `publish-release.yml` workflows.
- Removed `cache: yarn` configurations from all Node.js setup steps in `lint-build-test.yml`
- Updated `publish-release.yml` workflow to:
- Replace caching mechanism with GitHub Artifacts for build outputs
- Upgrade GitHub Actions to newer versions (`checkout@v4`, `setup-node@v4`)
- Remove the npm publish dry-run step for a more streamlined release process
- Implement proper artifact handling between jobs using `upload-artifact@v4` and `download-artifact@v4`
This change replaces the GitHub Actions caching mechanism with artifacts for managing build outputs between jobs. This provides more …

chore(security): remove GitHub Actions caching to prevent cache poisoning

---

packages/sdk-socket-server-next/src/analytics-api.ts
packages/sdk-socket-server-next/src/config.ts
packages/sdk-socket-server-next/src/logger.ts
packages/sdk-socket-server-next/src/protocol/handleMessage.ts

This PR reverts the socket server main code to match prod, and adds some configuration improvements for prod

Socket Server Fixes

---

packages/sdk-socket-server-next/src/logger.ts

This PR fixes the following type errors that surfaced during deployment
```shell
#12 [builder 6/6] RUN yarn build
#12 0.231 yarn run v1.22.22
#12 0.276 $ tsc
#12 4.061 src/logger.ts(26,9): error TS2339: Property 'map' does not exist on type '{}'.
#12 4.063 src/logger.ts(35,7): error TS18046: 'searchContext' is of type 'unknown'.
#12 4.063 src/logger.ts(38,14): error TS18046: 'searchContext' is of type 'unknown'.
#12 4.092 error Command failed with exit code 2.
#12 4.093 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
#12 ERROR: process "/bin/sh -c yarn build" did not complete successfully: exit code: 2
------
> [builder 6/6] RUN yarn build:
0.231 yarn run v1.22.22
0.276 $ tsc
4.061 src/logger.ts(26,9): error TS2339: Property 'map' does not exist on …
```

fix(socket): type errors

---

packages/sdk/src/config.ts

This PR fixes sending analytics when using extension and inapp-browser. 
Before this fix all these methods were being tracked when using one of these two platforms:
- eth_requestAccounts
- eth_sendTransaction
- eth_signTransaction
- eth_sign
- personal_sign
- eth_signTypedData
- eth_signTypedData_v3
- eth_signTypedData_v4
- wallet_requestPermissions
- wallet_getPermissions
- wallet_watchAsset
- wallet_addEthereumChain
- wallet_switchEthereumChain
- metamask_connectSign
- metamask_connectWith
- personal_ecRecover
- metamask_batch
- metamask_open
These methods are not being bypassed as they are being cached on the dapp side and not redirection occurs:
- eth_accounts
- eth_chainId

fix: Fix analytics for unwanted events when using extension

---

.github/workflows/publish-release.yml

This PR brings back some of the `publish-npm-dry-run` removed by this [PR](https://github.com/MetaMask/metamask-sdk/pull/1209/files#diff-8b87cbf4077dc8eb1e5e1dd371b96d601e94a8cb3cbeb8ff4096779dd65e2a44) which includes sending a notification via Slack.

fix: reverts the removal of some publish steps

---

packages/sdk-socket-server-next/src/analytics-api.ts

This PR updates the redis cluster config to reconnect on `MOVED` errors

fix(socket): reconnect on moved errors

---

packages/sdk-socket-server-next/src/protocol/handleAck.ts
packages/sdk-socket-server-next/src/protocol/handleChannelRejected.ts
packages/sdk-socket-server-next/src/protocol/handleCheckRoom.ts
packages/sdk-socket-server-next/src/protocol/handleJoinChannel.ts
packages/sdk-socket-server-next/src/protocol/handleMessage.ts
packages/sdk-socket-server-next/src/protocol/retrieveMessages.ts
packages/sdk-socket-server-next/src/socket-config.ts

This PR does a couple of things
* Adds redis [hash tags](https://redis.io/docs/latest/operate/oss_and_stack/reference/cluster-spec/#hash-tags) to enforce similar keys to fall under the same slot allocation group (by hashing the channelId whenever possible)
* Converts the global `channels` key (which kept track of channel occupancy) to a per-channel key

fix(socket|redis): convert global channels key to per-channel key and use hash tags

---

packages/sdk-socket-server-next/src/analytics-api.ts

Only want to filter out `"sdk_rpc_request_done"` and `"sdk_rpc_request"` events when their `method` isn’t in a specific allowlist. This change adds a filter to the `/evt` endpoint to silently drop these RPC events if their method isn’t one of: `"eth_sendTransaction"`, `"wallet_switchEthereumChain"`, `"personal_sign"`, `"eth_signTypedData_v4"`, `"wallet_requestPermissions"`, `"wallet_watchAsset"`, or `"metamask_connectSign"`. All other events pass through unchanged. 
- No specific issues tied to this PR.

fix(analytics): filter out some events

---

packages/sdk-socket-server-next/package.json
packages/sdk-socket-server-next/src/analytics-api.ts
packages/sdk-socket-server-next/src/protocol/handleChannelRejected.ts
packages/sdk-socket-server-next/src/protocol/handleJoinChannel.ts
packages/sdk-socket-server-next/src/redis-check.ts
packages/sdk-socket-server-next/src/socket-config.ts
yarn.lock

This PR introduces a client pool to allow some write operations to be performed by their own redis client without pipelining. The redis client pool size has a minimum of 15 connections and a maximum of 35 connections. Currently, the client pool is only used in 3 places, `leave-room`, `handleJoinChannel` and `handleChannelReject`

Use client pool for redis connections

---

packages/sdk-socket-server-next/src/protocol/handleJoinChannel.ts

There is a race condition between setting and getting a value in redis that some part of the protocol relies on. This PR adds artificial delay as a short term fix.

Relay Server - Fix race condition

---

packages/sdk-analytics/package.json

Just adding the publishConfig to publish a package inside a namespace @metamask. Required to publish the package in npm registry.

fix: add publishConfig too release for sdk-analytics package

---

package.json
packages/sdk-analytics/CHANGELOG.md
packages/sdk-analytics/package.json

- fix: add publishConfig too release for sdk-analytics package ([#1284](https://github.com/MetaMask/metamask-sdk/pull/1284))

Release 112.0.0

---

packages/sdk-analytics/src/analytics.ts
packages/sdk-analytics/src/sender.test.ts
packages/sdk-analytics/src/sender.ts

This PR addresses a bug in the analytics sender logic and improves design by switching from interval-based to timeout-based scheduling. Additionally, tests now use fake timers for faster execution.
- **Bug Fix**: Fixed an issue where the sender would not send events properly under certain conditions.
- **Timeout-Based Logic**: Replaced interval-based scheduling with timeout-based logic in `Sender`.
- **Fake Timers in Tests**: Updated `sender.test.ts` to use fake timers, significantly speeding up test execution.
- **Test Updates**: Adjusted test cases to align with the new timeout-based logic and improved test reliability.
- No specific issues tied to this PR.

Refactor sdk-analytics

---

packages/sdk-multichain/src/domain/store/client.ts
packages/sdk-multichain/src/store/adapters/node.ts
packages/sdk-multichain/src/store/adapters/rn.ts
packages/sdk-multichain/src/store/adapters/web.ts
packages/sdk-multichain/src/store/index.test.ts
packages/sdk-multichain/src/store/index.ts

Storage adapters are used by the SDK and dApps to store specific values in the native storage, example, the anonId needed for Analytics. 
This PR integrates the Storage wrapper, a simple class that will be used across the SDK to abstract from the storage and provide a simple to use interface with, setAnonId, removeAnonId and other utility functions for other attributes.
We also integrate 3 different storages, RN, Browser and Node.
RN is using internally @react-native-async-storage/async-storage
Browser is using internally localstorage
Node is using internally FS
Added basic unitary test coverage

fix: multichain core - stores adapters and client implementation

---

packages/sdk-multichain/src/connect.test.ts
packages/sdk-multichain/src/domain/events/types/index.ts
packages/sdk-multichain/src/init.test.ts
packages/sdk-multichain/src/multichain/index.ts
packages/sdk-multichain/src/session.test.ts

The display_uri event is still not in use. The event is used when headless: true is enabled and will trigger an event when we should be displaying the modal with the QRCode.
SessionChange event is renamed to session_change and the code is improved to use that one instead of the camelCase version

fix: use underscore for all event names and adjust tests + trigger

---

packages/sdk-analytics/package.json

Adding missing esmodule export in analytics package json.
If a library using Analytics requests esm the file will not be available and cause some exceptions.

fix: missing export of esmodule on sdk-analytics
